// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateClusterHook provides a mock function with given fields: ctx, ch
func (_m *MockService) CreateClusterHook(ctx context.Context, ch *v1alpha1.ClusterHook) (*v1alpha1.ClusterHook, error) {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterHook")
	}

	var r0 *v1alpha1.ClusterHook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterHook) (*v1alpha1.ClusterHook, error)); ok {
		return rf(ctx, ch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterHook) *v1alpha1.ClusterHook); ok {
		r0 = rf(ctx, ch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterHook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterHook) error); ok {
		r1 = rf(ctx, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateClusterHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterHook'
type MockService_CreateClusterHook_Call struct {
	*mock.Call
}

// CreateClusterHook is a helper method to define mock.On call
//   - ctx context.Context
//   - ch *v1alpha1.ClusterHook
func (_e *MockService_Expecter) CreateClusterHook(ctx interface{}, ch interface{}) *MockService_CreateClusterHook_Call {
	return &MockService_CreateClusterHook_Call{Call: _e.mock.On("CreateClusterHook", ctx, ch)}
}

func (_c *MockService_CreateClusterHook_Call) Run(run func(ctx context.Context, ch *v1alpha1.ClusterHook)) *MockService_CreateClusterHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.ClusterHook))
	})
	return _c
}

func (_c *MockService_CreateClusterHook_Call) Return(_a0 *v1alpha1.ClusterHook, _a1 error) *MockService_CreateClusterHook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateClusterHook_Call) RunAndReturn(run func(context.Context, *v1alpha1.ClusterHook) (*v1alpha1.ClusterHook, error)) *MockService_CreateClusterHook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClusterHook provides a mock function with given fields: ctx, clusterHookName
func (_m *MockService) DeleteClusterHook(ctx context.Context, clusterHookName string) error {
	ret := _m.Called(ctx, clusterHookName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClusterHook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clusterHookName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteClusterHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClusterHook'
type MockService_DeleteClusterHook_Call struct {
	*mock.Call
}

// DeleteClusterHook is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterHookName string
func (_e *MockService_Expecter) DeleteClusterHook(ctx interface{}, clusterHookName interface{}) *MockService_DeleteClusterHook_Call {
	return &MockService_DeleteClusterHook_Call{Call: _e.mock.On("DeleteClusterHook", ctx, clusterHookName)}
}

func (_c *MockService_DeleteClusterHook_Call) Run(run func(ctx context.Context, clusterHookName string)) *MockService_DeleteClusterHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteClusterHook_Call) Return(_a0 error) *MockService_DeleteClusterHook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteClusterHook_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteClusterHook_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterHook provides a mock function with given fields: ctx, clusterHookName
func (_m *MockService) GetClusterHook(ctx context.Context, clusterHookName string) (*v1alpha1.ClusterHook, error) {
	ret := _m.Called(ctx, clusterHookName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterHook")
	}

	var r0 *v1alpha1.ClusterHook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1alpha1.ClusterHook, error)); ok {
		return rf(ctx, clusterHookName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1alpha1.ClusterHook); ok {
		r0 = rf(ctx, clusterHookName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterHook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterHookName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetClusterHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterHook'
type MockService_GetClusterHook_Call struct {
	*mock.Call
}

// GetClusterHook is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterHookName string
func (_e *MockService_Expecter) GetClusterHook(ctx interface{}, clusterHookName interface{}) *MockService_GetClusterHook_Call {
	return &MockService_GetClusterHook_Call{Call: _e.mock.On("GetClusterHook", ctx, clusterHookName)}
}

func (_c *MockService_GetClusterHook_Call) Run(run func(ctx context.Context, clusterHookName string)) *MockService_GetClusterHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetClusterHook_Call) Return(_a0 *v1alpha1.ClusterHook, _a1 error) *MockService_GetClusterHook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetClusterHook_Call) RunAndReturn(run func(context.Context, string) (*v1alpha1.ClusterHook, error)) *MockService_GetClusterHook_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusterHooks provides a mock function with given fields: ctx, opts
func (_m *MockService) ListClusterHooks(ctx context.Context, opts services.ListOptions) (*services.ListResult[v1alpha1.ClusterHook], error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListClusterHooks")
	}

	var r0 *services.ListResult[v1alpha1.ClusterHook]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ListOptions) (*services.ListResult[v1alpha1.ClusterHook], error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.ListOptions) *services.ListResult[v1alpha1.ClusterHook]); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ClusterHook])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListClusterHooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusterHooks'
type MockService_ListClusterHooks_Call struct {
	*mock.Call
}

// ListClusterHooks is a helper method to define mock.On call
//   - ctx context.Context
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListClusterHooks(ctx interface{}, opts interface{}) *MockService_ListClusterHooks_Call {
	return &MockService_ListClusterHooks_Call{Call: _e.mock.On("ListClusterHooks", ctx, opts)}
}

func (_c *MockService_ListClusterHooks_Call) Run(run func(ctx context.Context, opts services.ListOptions)) *MockService_ListClusterHooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListClusterHooks_Call) Return(_a0 *services.ListResult[v1alpha1.ClusterHook], _a1 error) *MockService_ListClusterHooks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListClusterHooks_Call) RunAndReturn(run func(context.Context, services.ListOptions) (*services.ListResult[v1alpha1.ClusterHook], error)) *MockService_ListClusterHooks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClusterHook provides a mock function with given fields: ctx, ch
func (_m *MockService) UpdateClusterHook(ctx context.Context, ch *v1alpha1.ClusterHook) (*v1alpha1.ClusterHook, error) {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClusterHook")
	}

	var r0 *v1alpha1.ClusterHook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterHook) (*v1alpha1.ClusterHook, error)); ok {
		return rf(ctx, ch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterHook) *v1alpha1.ClusterHook); ok {
		r0 = rf(ctx, ch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterHook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterHook) error); ok {
		r1 = rf(ctx, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateClusterHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClusterHook'
type MockService_UpdateClusterHook_Call struct {
	*mock.Call
}

// UpdateClusterHook is a helper method to define mock.On call
//   - ctx context.Context
//   - ch *v1alpha1.ClusterHook
func (_e *MockService_Expecter) UpdateClusterHook(ctx interface{}, ch interface{}) *MockService_UpdateClusterHook_Call {
	return &MockService_UpdateClusterHook_Call{Call: _e.mock.On("UpdateClusterHook", ctx, ch)}
}

func (_c *MockService_UpdateClusterHook_Call) Run(run func(ctx context.Context, ch *v1alpha1.ClusterHook)) *MockService_UpdateClusterHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.ClusterHook))
	})
	return _c
}

func (_c *MockService_UpdateClusterHook_Call) Return(_a0 *v1alpha1.ClusterHook, _a1 error) *MockService_UpdateClusterHook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateClusterHook_Call) RunAndReturn(run func(context.Context, *v1alpha1.ClusterHook) (*v1alpha1.ClusterHook, error)) *MockService_UpdateClusterHook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
