---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kube-apiserver
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "openchoreo-observability-plane.chart" . }}
    release: {{ .Release.Name }}  # Required for Prometheus discovery
spec:
  selector:
    matchLabels:
      k8s-app: kube-apiserver
  endpoints:
  - port: https
    path: /metrics
    interval: 30s
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - kube-system
