---
apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-apiserver
    k8s-app: kube-apiserver
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "openchoreo-observability-plane.chart" . }}
spec:
  clusterIP: None  # Headless service
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: 6443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-apiserver
    k8s-app: kube-apiserver
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "openchoreo-observability-plane.chart" . }}
subsets:
- addresses:
  # Kind cluster API server endpoint
  - ip: 172.18.0.2  # Kind control plane node IP
  ports:
  - name: https
    port: 6443
    protocol: TCP
