apiVersion: openchoreo.dev/v1alpha1
kind: Addon
metadata:
  name: simple-pvc
  namespace: default
spec:
  schema:
    # Developer-facing parameters
    parameters:
      volumeName: "string | required=true"
      mountPath: "string | required=true"
      containerName: "string"

    # Environment-specific overrides
    envOverrides:
      size: "string | default=10Gi"
      storageClass: "string | default=standard"

  # New resources created by this addon
  creates:
    - template:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: ${metadata.name}-${instanceId}
          namespace: ${metadata.namespace}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: ${spec.size}
          storageClassName: ${spec.storageClass}

  # Patches to apply to existing resources
  patches:
    # Add volume to deployment
    - target:
        group: apps
        version: v1
        kind: Deployment
      operations:
        - op: add
          path: /spec/template/spec/volumes/-
          value:
            name: ${spec.volumeName}
            persistentVolumeClaim:
              claimName: ${metadata.name}-${instanceId}

    # Mount volume to container
    - target:
        group: apps
        version: v1
        kind: Deployment
      operations:
        - op: add
          path: /spec/template/spec/containers/[?(@.name=='${spec.containerName}')]/volumeMounts/-
          value:
            name: ${spec.volumeName}
            mountPath: ${spec.mountPath}
