apiVersion: openchoreo.dev/v1alpha1
kind: ComponentTypeDefinition
metadata:
  name: web-service
  namespace: default
spec:
  workloadType: deployment

  schema:
    parameters:
      replicas: "integer | default=1"
      imagePullPolicy: "string | default=IfNotPresent"
      port: "integer | default=8080"

    envOverrides:
      resources:
        requests:
          cpu: "string | default=100m"
          memory: "string | default=256Mi"
        limits:
          cpu: "string | default=500m"
          memory: "string | default=512Mi"

  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${metadata.name}
          namespace: ${metadata.namespace}
          labels: ${metadata.labels}
        spec:
          replicas: ${parameters.replicas}
          selector:
            matchLabels: ${metadata.podSelectors}
          template:
            metadata:
              labels: ${metadata.podSelectors}
            spec:
              containers:
                - name: app
                  image: ${workload.containers["app"].image}
                  imagePullPolicy: ${parameters.imagePullPolicy}
                  ports:
                    - name: http
                      containerPort: ${parameters.port}
                      protocol: TCP
                  resources:
                    requests:
                      cpu: ${parameters.resources.requests.cpu}
                      memory: ${parameters.resources.requests.memory}
                    limits:
                      cpu: ${parameters.resources.limits.cpu}
                      memory: ${parameters.resources.limits.memory}

    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${metadata.name}
          namespace: ${metadata.namespace}
          labels: ${metadata.labels}
        spec:
          type: ClusterIP
          selector: ${metadata.podSelectors}
          ports:
            - name: http
              port: 80
              targetPort: ${parameters.port}
              protocol: TCP

---
apiVersion: openchoreo.dev/v1alpha1
kind: Addon
metadata:
  name: persistent-volume
  namespace: default
spec:
  schema:
    parameters:
      volumeName: "string | required=true"
      mountPath: "string | required=true"
      containerName: "string | default=app"

    envOverrides:
      size: "string | default=10Gi"
      storageClass: "string | default=standard"

  creates:
    - template:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: ${metadata.name}-${addon.instanceName}
          namespace: ${metadata.namespace}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: ${parameters.size}
          storageClassName: ${parameters.storageClass}

  patches:
    - target:
        group: apps
        version: v1
        kind: Deployment
      operations:
        - op: add
          path: /spec/template/spec/volumes/-
          value:
            name: ${parameters.volumeName}
            persistentVolumeClaim:
              claimName: ${metadata.name}-${addon.instanceName}

    - target:
        group: apps
        version: v1
        kind: Deployment
      operations:
        - op: add
          path: /spec/template/spec/containers/[?(@.name=='${parameters.containerName}')]/volumeMounts/-
          value:
            name: ${parameters.volumeName}
            mountPath: ${parameters.mountPath}

---
apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: demo-app
  namespace: default
spec:
  owner:
    projectName: default

  componentType: deployment/web-service

  parameters:
    replicas: 2
    port: 8080
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  addons:
    - name: persistent-volume
      instanceName: data-storage
      config:
        volumeName: app-data
        mountPath: /var/data
        containerName: app
        size: "20Gi"
        storageClass: "fast"

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: demo-app-workload
  namespace: default
spec:
  owner:
    projectName: default
    componentName: demo-app

  containers:
    app:
      image: "nginx:1.25-alpine"

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: demo-app-development
  namespace: default
spec:
  owner:
    projectName: default
    componentName: demo-app

  environment: development

  overrides:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

  addonOverrides:
    data-storage:
      size: "5Gi"
      storageClass: "standard"
