// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/openchoreo/openchoreo/internal/observer/types"
)

// MockClusterLogsQuerier is an autogenerated mock type for the ClusterLogsQuerier type
type MockClusterLogsQuerier struct {
	mock.Mock
}

type MockClusterLogsQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterLogsQuerier) EXPECT() *MockClusterLogsQuerier_Expecter {
	return &MockClusterLogsQuerier_Expecter{mock: &_m.Mock}
}

// QueryClusterLogs provides a mock function with given fields: ctx, req
func (_m *MockClusterLogsQuerier) QueryClusterLogs(ctx context.Context, req *types.ClusterLogsQueryRequest) (*types.ClusterLogsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryClusterLogs")
	}

	var r0 *types.ClusterLogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.ClusterLogsQueryRequest) (*types.ClusterLogsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.ClusterLogsQueryRequest) *types.ClusterLogsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ClusterLogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.ClusterLogsQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterLogsQuerier_QueryClusterLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryClusterLogs'
type MockClusterLogsQuerier_QueryClusterLogs_Call struct {
	*mock.Call
}

// QueryClusterLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - req *types.ClusterLogsQueryRequest
func (_e *MockClusterLogsQuerier_Expecter) QueryClusterLogs(ctx interface{}, req interface{}) *MockClusterLogsQuerier_QueryClusterLogs_Call {
	return &MockClusterLogsQuerier_QueryClusterLogs_Call{Call: _e.mock.On("QueryClusterLogs", ctx, req)}
}

func (_c *MockClusterLogsQuerier_QueryClusterLogs_Call) Run(run func(ctx context.Context, req *types.ClusterLogsQueryRequest)) *MockClusterLogsQuerier_QueryClusterLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.ClusterLogsQueryRequest))
	})
	return _c
}

func (_c *MockClusterLogsQuerier_QueryClusterLogs_Call) Return(_a0 *types.ClusterLogsResponse, _a1 error) *MockClusterLogsQuerier_QueryClusterLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterLogsQuerier_QueryClusterLogs_Call) RunAndReturn(run func(context.Context, *types.ClusterLogsQueryRequest) (*types.ClusterLogsResponse, error)) *MockClusterLogsQuerier_QueryClusterLogs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClusterLogsQuerier creates a new instance of MockClusterLogsQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterLogsQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterLogsQuerier {
	mock := &MockClusterLogsQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
