// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateComponentReleaseBinding provides a mock function with given fields: ctx, namespaceName, rb
func (_m *MockService) CreateComponentReleaseBinding(ctx context.Context, namespaceName string, rb *v1alpha1.ComponentReleaseBinding) (*v1alpha1.ComponentReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, rb)

	if len(ret) == 0 {
		panic("no return value specified for CreateComponentReleaseBinding")
	}

	var r0 *v1alpha1.ComponentReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ComponentReleaseBinding) (*v1alpha1.ComponentReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, rb)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ComponentReleaseBinding) *v1alpha1.ComponentReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, rb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ComponentReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ComponentReleaseBinding) error); ok {
		r1 = rf(ctx, namespaceName, rb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateComponentReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComponentReleaseBinding'
type MockService_CreateComponentReleaseBinding_Call struct {
	*mock.Call
}

// CreateComponentReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rb *v1alpha1.ComponentReleaseBinding
func (_e *MockService_Expecter) CreateComponentReleaseBinding(ctx interface{}, namespaceName interface{}, rb interface{}) *MockService_CreateComponentReleaseBinding_Call {
	return &MockService_CreateComponentReleaseBinding_Call{Call: _e.mock.On("CreateComponentReleaseBinding", ctx, namespaceName, rb)}
}

func (_c *MockService_CreateComponentReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, rb *v1alpha1.ComponentReleaseBinding)) *MockService_CreateComponentReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ComponentReleaseBinding))
	})
	return _c
}

func (_c *MockService_CreateComponentReleaseBinding_Call) Return(_a0 *v1alpha1.ComponentReleaseBinding, _a1 error) *MockService_CreateComponentReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateComponentReleaseBinding_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ComponentReleaseBinding) (*v1alpha1.ComponentReleaseBinding, error)) *MockService_CreateComponentReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComponentReleaseBinding provides a mock function with given fields: ctx, namespaceName, componentReleaseBindingName
func (_m *MockService) DeleteComponentReleaseBinding(ctx context.Context, namespaceName string, componentReleaseBindingName string) error {
	ret := _m.Called(ctx, namespaceName, componentReleaseBindingName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponentReleaseBinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, componentReleaseBindingName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteComponentReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponentReleaseBinding'
type MockService_DeleteComponentReleaseBinding_Call struct {
	*mock.Call
}

// DeleteComponentReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentReleaseBindingName string
func (_e *MockService_Expecter) DeleteComponentReleaseBinding(ctx interface{}, namespaceName interface{}, componentReleaseBindingName interface{}) *MockService_DeleteComponentReleaseBinding_Call {
	return &MockService_DeleteComponentReleaseBinding_Call{Call: _e.mock.On("DeleteComponentReleaseBinding", ctx, namespaceName, componentReleaseBindingName)}
}

func (_c *MockService_DeleteComponentReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, componentReleaseBindingName string)) *MockService_DeleteComponentReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteComponentReleaseBinding_Call) Return(_a0 error) *MockService_DeleteComponentReleaseBinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteComponentReleaseBinding_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteComponentReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentReleaseBinding provides a mock function with given fields: ctx, namespaceName, componentReleaseBindingName
func (_m *MockService) GetComponentReleaseBinding(ctx context.Context, namespaceName string, componentReleaseBindingName string) (*v1alpha1.ComponentReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, componentReleaseBindingName)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentReleaseBinding")
	}

	var r0 *v1alpha1.ComponentReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ComponentReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, componentReleaseBindingName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ComponentReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, componentReleaseBindingName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ComponentReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, componentReleaseBindingName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetComponentReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentReleaseBinding'
type MockService_GetComponentReleaseBinding_Call struct {
	*mock.Call
}

// GetComponentReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentReleaseBindingName string
func (_e *MockService_Expecter) GetComponentReleaseBinding(ctx interface{}, namespaceName interface{}, componentReleaseBindingName interface{}) *MockService_GetComponentReleaseBinding_Call {
	return &MockService_GetComponentReleaseBinding_Call{Call: _e.mock.On("GetComponentReleaseBinding", ctx, namespaceName, componentReleaseBindingName)}
}

func (_c *MockService_GetComponentReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, componentReleaseBindingName string)) *MockService_GetComponentReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetComponentReleaseBinding_Call) Return(_a0 *v1alpha1.ComponentReleaseBinding, _a1 error) *MockService_GetComponentReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetComponentReleaseBinding_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ComponentReleaseBinding, error)) *MockService_GetComponentReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponentComponentReleaseBindings provides a mock function with given fields: ctx, namespaceName, componentName, opts
func (_m *MockService) ListComponentComponentReleaseBindings(ctx context.Context, namespaceName string, componentName string, opts services.ListOptions) (*services.ListResult[v1alpha1.ComponentReleaseBinding], error) {
	ret := _m.Called(ctx, namespaceName, componentName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListComponentComponentReleaseBindings")
	}

	var r0 *services.ListResult[v1alpha1.ComponentReleaseBinding]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ComponentReleaseBinding], error)); ok {
		return rf(ctx, namespaceName, componentName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) *services.ListResult[v1alpha1.ComponentReleaseBinding]); ok {
		r0 = rf(ctx, namespaceName, componentName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ComponentReleaseBinding])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, componentName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListComponentComponentReleaseBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponentComponentReleaseBindings'
type MockService_ListComponentComponentReleaseBindings_Call struct {
	*mock.Call
}

// ListComponentComponentReleaseBindings is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListComponentComponentReleaseBindings(ctx interface{}, namespaceName interface{}, componentName interface{}, opts interface{}) *MockService_ListComponentComponentReleaseBindings_Call {
	return &MockService_ListComponentComponentReleaseBindings_Call{Call: _e.mock.On("ListComponentComponentReleaseBindings", ctx, namespaceName, componentName, opts)}
}

func (_c *MockService_ListComponentComponentReleaseBindings_Call) Run(run func(ctx context.Context, namespaceName string, componentName string, opts services.ListOptions)) *MockService_ListComponentComponentReleaseBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListComponentComponentReleaseBindings_Call) Return(_a0 *services.ListResult[v1alpha1.ComponentReleaseBinding], _a1 error) *MockService_ListComponentComponentReleaseBindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListComponentComponentReleaseBindings_Call) RunAndReturn(run func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ComponentReleaseBinding], error)) *MockService_ListComponentComponentReleaseBindings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComponentReleaseBinding provides a mock function with given fields: ctx, namespaceName, rb
func (_m *MockService) UpdateComponentReleaseBinding(ctx context.Context, namespaceName string, rb *v1alpha1.ComponentReleaseBinding) (*v1alpha1.ComponentReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, rb)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComponentReleaseBinding")
	}

	var r0 *v1alpha1.ComponentReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ComponentReleaseBinding) (*v1alpha1.ComponentReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, rb)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ComponentReleaseBinding) *v1alpha1.ComponentReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, rb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ComponentReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ComponentReleaseBinding) error); ok {
		r1 = rf(ctx, namespaceName, rb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateComponentReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponentReleaseBinding'
type MockService_UpdateComponentReleaseBinding_Call struct {
	*mock.Call
}

// UpdateComponentReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rb *v1alpha1.ComponentReleaseBinding
func (_e *MockService_Expecter) UpdateComponentReleaseBinding(ctx interface{}, namespaceName interface{}, rb interface{}) *MockService_UpdateComponentReleaseBinding_Call {
	return &MockService_UpdateComponentReleaseBinding_Call{Call: _e.mock.On("UpdateComponentReleaseBinding", ctx, namespaceName, rb)}
}

func (_c *MockService_UpdateComponentReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, rb *v1alpha1.ComponentReleaseBinding)) *MockService_UpdateComponentReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ComponentReleaseBinding))
	})
	return _c
}

func (_c *MockService_UpdateComponentReleaseBinding_Call) Return(_a0 *v1alpha1.ComponentReleaseBinding, _a1 error) *MockService_UpdateComponentReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateComponentReleaseBinding_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ComponentReleaseBinding) (*v1alpha1.ComponentReleaseBinding, error)) *MockService_UpdateComponentReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
