// Copyright 2025 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	DeleteScannedPod(ctx context.Context, id int32) error
	GetScannedPod(ctx context.Context, id int32) (ScannedPod, error)
	GetScannedPodByName(ctx context.Context, podName string) (ScannedPod, error)
	InsertScannedPod(ctx context.Context, podName string) error
	ListScannedPods(ctx context.Context) ([]ScannedPod, error)
}

var _ Querier = (*Queries)(nil)
