apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: redis
  annotations:
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
