# permissions for end users to view secretreferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openchoreo
    app.kubernetes.io/managed-by: kustomize
  name: secretreference-viewer-role
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - secretreferences
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - secretreferences/status
  verbs:
  - get
