name: Bug Report
description: Report a bug encountered while using the Choreo
labels:
  - type/bug
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear summary of the issue, including what happened,
        what do you expected to happen, and any error messages encountered.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Details about the environment such as the Kubernetes version, Container Runtime version, and any other relevant information
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information that may be helpful in diagnosing the bug
