// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type PostureFinding struct {
	ID              int64          `json:"id"`
	ResourceID      int64          `json:"resource_id"`
	CheckID         string         `json:"check_id"`
	CheckName       string         `json:"check_name"`
	Severity        string         `json:"severity"`
	Category        sql.NullString `json:"category"`
	Description     sql.NullString `json:"description"`
	Remediation     sql.NullString `json:"remediation"`
	ResourceVersion string         `json:"resource_version"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type PostureScannedResource struct {
	ID              int64         `json:"id"`
	ResourceID      int64         `json:"resource_id"`
	ResourceVersion string        `json:"resource_version"`
	ScanDurationMs  sql.NullInt64 `json:"scan_duration_ms"`
	ScannedAt       sql.NullTime  `json:"scanned_at"`
}

type Resource struct {
	ID                int64        `json:"id"`
	ResourceType      string       `json:"resource_type"`
	ResourceNamespace string       `json:"resource_namespace"`
	ResourceName      string       `json:"resource_name"`
	ResourceUid       string       `json:"resource_uid"`
	ResourceVersion   string       `json:"resource_version"`
	CreatedAt         sql.NullTime `json:"created_at"`
	UpdatedAt         sql.NullTime `json:"updated_at"`
}

type ResourceLabel struct {
	ID         int64  `json:"id"`
	ResourceID int64  `json:"resource_id"`
	LabelKey   string `json:"label_key"`
	LabelValue string `json:"label_value"`
}
