// Copyright 2025 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

type ScannedPod struct {
	ID      int64  `json:"id"`
	PodName string `json:"pod_name"`
}

func (s ScannedPod) GetID() int64 {
	return s.ID
}

func (s ScannedPod) GetPodName() string {
	return s.PodName
}
