// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	DeletePostureFindingsByResourceID(ctx context.Context, resourceID int64) error
	DeleteResourceLabels(ctx context.Context, resourceID int64) error
	GetPostureScannedResource(ctx context.Context, arg GetPostureScannedResourceParams) (PostureScannedResource, error)
	InsertPostureFinding(ctx context.Context, arg InsertPostureFindingParams) error
	InsertResourceLabel(ctx context.Context, arg InsertResourceLabelParams) error
	ListPostureFindings(ctx context.Context, arg ListPostureFindingsParams) ([]ListPostureFindingsRow, error)
	UpsertPostureScannedResource(ctx context.Context, arg UpsertPostureScannedResourceParams) error
	UpsertResource(ctx context.Context, arg UpsertResourceParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
