// Copyright 2025 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	CountResourcesWithPostureFindings(ctx context.Context) (int64, error)
	DeletePostureFindingsByResourceID(ctx context.Context, resourceID int64) error
	DeleteResourceLabels(ctx context.Context, resourceID int64) error
	GetPostureFindingsByResourceID(ctx context.Context, resourceID int64) ([]PostureFinding, error)
	GetPostureScannedResource(ctx context.Context, arg GetPostureScannedResourceParams) (PostureScannedResource, error)
	GetResource(ctx context.Context, id int64) (Resource, error)
	GetResourceLabels(ctx context.Context, resourceID int64) ([]GetResourceLabelsRow, error)
	InsertPostureFinding(ctx context.Context, arg InsertPostureFindingParams) error
	InsertResourceLabel(ctx context.Context, arg InsertResourceLabelParams) error
	ListPostureFindings(ctx context.Context, arg ListPostureFindingsParams) ([]ListPostureFindingsRow, error)
	ListResourcesWithPostureFindings(ctx context.Context, arg ListResourcesWithPostureFindingsParams) ([]Resource, error)
	UpsertPostureScannedResource(ctx context.Context, arg UpsertPostureScannedResourceParams) error
	UpsertResource(ctx context.Context, arg UpsertResourceParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
