apiVersion: v2
name: openchoreo-identity-provider
description: A Helm chart for OpenChoreo Identity Provider
type: application
# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"
keywords:
  - identity
  - oauth
  - authentication
  - openchoreo
home: https://github.com/openchoreo/openchoreo
sources:
  - https://github.com/openchoreo/openchoreo
maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo

dependencies:
  - name: openchoreo-common
    version: "0.0.0-latest-dev"
    repository: "file://../openchoreo-common"
