---
apiVersion: v1
kind: Service
metadata:
  name: kubelet
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
    app.kubernetes.io/component: kubelet
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "openchoreo-observability-plane.chart" . }}
spec:
  type: ClusterIP
  clusterIP: None  # Headless service
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
    targetPort: 10250
  - name: http-metrics
    port: 10255
    protocol: TCP
    targetPort: 10255
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kubelet
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
    app.kubernetes.io/component: kubelet
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "openchoreo-observability-plane.chart" . }}
subsets:
- addresses:
  {{- range $node := (lookup "v1" "Node" "" "").items }}
  - ip: {{ range $addr := $node.status.addresses }}{{ if eq $addr.type "InternalIP" }}{{ $addr.address }}{{ end }}{{ end }}
    nodeName: {{ $node.metadata.name }}
  {{- end }}
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
  - name: http-metrics
    port: 10255
    protocol: TCP