{{ if .Values.global.defaultResources.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-argo-crds
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: wait-for-crds
      containers:
      - name: wait-for-crds
        image: {{ .Values.global.waitJob.image }}
        imagePullPolicy: IfNotPresent
        command:
          - kubectl
        args:
          - wait
          - --for=condition=Established
          - crd/clusterworkflowtemplates.argoproj.io
          - crd/workflowtemplates.argoproj.io
          - crd/workflows.argoproj.io
          - --timeout=300s
  backoffLimit: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-for-crds
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wait-for-crds
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wait-for-crds
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wait-for-crds
subjects:
- kind: ServiceAccount
  name: wait-for-crds
  namespace: {{ .Release.Namespace }}
{{ end }}
