//go:build go1.22

// Package internalgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package internalgen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/openchoreo/openchoreo/internal/observer/api/gen"
)

// Defines values for AlertRuleRequestConditionOperator.
const (
	AlertRuleRequestConditionOperatorEq  AlertRuleRequestConditionOperator = "eq"
	AlertRuleRequestConditionOperatorGt  AlertRuleRequestConditionOperator = "gt"
	AlertRuleRequestConditionOperatorGte AlertRuleRequestConditionOperator = "gte"
	AlertRuleRequestConditionOperatorLt  AlertRuleRequestConditionOperator = "lt"
	AlertRuleRequestConditionOperatorLte AlertRuleRequestConditionOperator = "lte"
	AlertRuleRequestConditionOperatorNeq AlertRuleRequestConditionOperator = "neq"
)

// Defines values for AlertRuleRequestSourceMetric.
const (
	AlertRuleRequestSourceMetricBudget      AlertRuleRequestSourceMetric = "budget"
	AlertRuleRequestSourceMetricCpuUsage    AlertRuleRequestSourceMetric = "cpu_usage"
	AlertRuleRequestSourceMetricMemoryUsage AlertRuleRequestSourceMetric = "memory_usage"
)

// Defines values for AlertRuleRequestSourceType.
const (
	AlertRuleRequestSourceTypeBudget AlertRuleRequestSourceType = "budget"
	AlertRuleRequestSourceTypeLog    AlertRuleRequestSourceType = "log"
	AlertRuleRequestSourceTypeMetric AlertRuleRequestSourceType = "metric"
)

// Defines values for AlertRuleResponseConditionOperator.
const (
	AlertRuleResponseConditionOperatorEq  AlertRuleResponseConditionOperator = "eq"
	AlertRuleResponseConditionOperatorGt  AlertRuleResponseConditionOperator = "gt"
	AlertRuleResponseConditionOperatorGte AlertRuleResponseConditionOperator = "gte"
	AlertRuleResponseConditionOperatorLt  AlertRuleResponseConditionOperator = "lt"
	AlertRuleResponseConditionOperatorLte AlertRuleResponseConditionOperator = "lte"
	AlertRuleResponseConditionOperatorNeq AlertRuleResponseConditionOperator = "neq"
)

// Defines values for AlertRuleResponseSourceMetric.
const (
	AlertRuleResponseSourceMetricBudget      AlertRuleResponseSourceMetric = "budget"
	AlertRuleResponseSourceMetricCpuUsage    AlertRuleResponseSourceMetric = "cpu_usage"
	AlertRuleResponseSourceMetricMemoryUsage AlertRuleResponseSourceMetric = "memory_usage"
)

// Defines values for AlertRuleResponseSourceType.
const (
	AlertRuleResponseSourceTypeBudget AlertRuleResponseSourceType = "budget"
	AlertRuleResponseSourceTypeLog    AlertRuleResponseSourceType = "log"
	AlertRuleResponseSourceTypeMetric AlertRuleResponseSourceType = "metric"
)

// Defines values for AlertWebhookResponseStatus.
const (
	AlertWebhookResponseStatusError   AlertWebhookResponseStatus = "error"
	AlertWebhookResponseStatusSuccess AlertWebhookResponseStatus = "success"
)

// Defines values for AlertingRuleSyncResponseAction.
const (
	AlertingRuleSyncResponseActionCreated   AlertingRuleSyncResponseAction = "created"
	AlertingRuleSyncResponseActionDeleted   AlertingRuleSyncResponseAction = "deleted"
	AlertingRuleSyncResponseActionUnchanged AlertingRuleSyncResponseAction = "unchanged"
	AlertingRuleSyncResponseActionUpdated   AlertingRuleSyncResponseAction = "updated"
)

// Defines values for AlertingRuleSyncResponseStatus.
const (
	AlertingRuleSyncResponseStatusFailed AlertingRuleSyncResponseStatus = "failed"
	AlertingRuleSyncResponseStatusSynced AlertingRuleSyncResponseStatus = "synced"
)

// AlertRuleRequest defines model for AlertRuleRequest.
type AlertRuleRequest struct {
	Condition struct {
		// Enabled Whether the alert rule is enabled
		Enabled bool `json:"enabled"`

		// Interval The interval of time to query for the alert rule
		Interval string `json:"interval"`

		// Operator The operator to use for the alert rule
		Operator AlertRuleRequestConditionOperator `json:"operator"`

		// Threshold The threshold value to use for the alert rule
		Threshold float32 `json:"threshold"`

		// Window The window of time to query for the alert rule
		Window string `json:"window"`
	} `json:"condition"`
	Metadata struct {
		// ComponentUid The OpenChoreo component UID to query
		ComponentUid openapi_types.UUID `json:"componentUid"`

		// EnvironmentUid The OpenChoreo environment UID to query
		EnvironmentUid openapi_types.UUID `json:"environmentUid"`

		// Name The name of the alert rule
		Name string `json:"name"`

		// Namespace The namespace of the alert rule CR
		Namespace string `json:"namespace"`

		// ProjectUid The OpenChoreo project UID to query
		ProjectUid openapi_types.UUID `json:"projectUid"`
	} `json:"metadata"`
	Source struct {
		// Metric The metric to query for metric based alerts
		Metric *AlertRuleRequestSourceMetric `json:"metric,omitempty"`

		// Query The query to execute for log based alerts
		Query *string `json:"query,omitempty"`

		// Type The type of the source
		Type AlertRuleRequestSourceType `json:"type"`
	} `json:"source"`
}

// AlertRuleRequestConditionOperator The operator to use for the alert rule
type AlertRuleRequestConditionOperator string

// AlertRuleRequestSourceMetric The metric to query for metric based alerts
type AlertRuleRequestSourceMetric string

// AlertRuleRequestSourceType The type of the source
type AlertRuleRequestSourceType string

// AlertRuleResponse defines model for AlertRuleResponse.
type AlertRuleResponse struct {
	Condition *struct {
		// Enabled Whether the alert rule is enabled
		Enabled *bool `json:"enabled,omitempty"`

		// Interval The interval of time to query for the alert rule
		Interval *string `json:"interval,omitempty"`

		// Operator The operator to use for the alert rule
		Operator *AlertRuleResponseConditionOperator `json:"operator,omitempty"`

		// Threshold The threshold value to use for the alert rule
		Threshold *float32 `json:"threshold,omitempty"`

		// Window The window of time to query for the alert rule
		Window *string `json:"window,omitempty"`
	} `json:"condition,omitempty"`
	Metadata *struct {
		// ComponentUid The OpenChoreo component UID to query
		ComponentUid *openapi_types.UUID `json:"componentUid,omitempty"`

		// EnvironmentUid The OpenChoreo environment UID to query
		EnvironmentUid *openapi_types.UUID `json:"environmentUid,omitempty"`

		// Name The name of the alert rule
		Name *string `json:"name,omitempty"`

		// Namespace The namespace of the alert rule CR
		Namespace *string `json:"namespace,omitempty"`

		// ProjectUid The OpenChoreo project UID to query
		ProjectUid *openapi_types.UUID `json:"projectUid,omitempty"`
	} `json:"metadata,omitempty"`
	Source *struct {
		// Metric The metric to query for metric based alerts
		Metric *AlertRuleResponseSourceMetric `json:"metric,omitempty"`

		// Query The query to execute for log based alerts
		Query *string `json:"query,omitempty"`

		// Type The type of the source
		Type *AlertRuleResponseSourceType `json:"type,omitempty"`
	} `json:"source,omitempty"`
}

// AlertRuleResponseConditionOperator The operator to use for the alert rule
type AlertRuleResponseConditionOperator string

// AlertRuleResponseSourceMetric The metric to query for metric based alerts
type AlertRuleResponseSourceMetric string

// AlertRuleResponseSourceType The type of the source
type AlertRuleResponseSourceType string

// AlertWebhookRequest defines model for AlertWebhookRequest.
type AlertWebhookRequest struct {
	// AlertTimestamp The timestamp of the alert
	AlertTimestamp *time.Time `json:"alertTimestamp,omitempty"`

	// AlertValue The value of the alert
	AlertValue *float32 `json:"alertValue,omitempty"`

	// RuleName The name of the alert rule
	RuleName *string `json:"ruleName,omitempty"`

	// RuleNamespace The namespace of the alert rule
	RuleNamespace *string `json:"ruleNamespace,omitempty"`
}

// AlertWebhookResponse defines model for AlertWebhookResponse.
type AlertWebhookResponse struct {
	// Message The message of the alert webhook
	Message *string `json:"message,omitempty"`

	// Status The status of the alert webhook
	Status *AlertWebhookResponseStatus `json:"status,omitempty"`
}

// AlertWebhookResponseStatus The status of the alert webhook
type AlertWebhookResponseStatus string

// AlertingRuleSyncResponse defines model for AlertingRuleSyncResponse.
type AlertingRuleSyncResponse struct {
	// Action The action taken on the alert rule
	Action *AlertingRuleSyncResponseAction `json:"action,omitempty"`

	// LastSyncedAt The timestamp of the last sync
	LastSyncedAt *string `json:"lastSyncedAt,omitempty"`

	// RuleBackendId The backend ID (UID from observability backend) of the alert rule
	RuleBackendId *string `json:"ruleBackendId,omitempty"`

	// RuleLogicalId The logical ID (name) of the alert rule
	RuleLogicalId *string `json:"ruleLogicalId,omitempty"`

	// Status The status of the alert rule
	Status *AlertingRuleSyncResponseStatus `json:"status,omitempty"`
}

// AlertingRuleSyncResponseAction The action taken on the alert rule
type AlertingRuleSyncResponseAction string

// AlertingRuleSyncResponseStatus The status of the alert rule
type AlertingRuleSyncResponseStatus string

// CreateAlertRuleJSONRequestBody defines body for CreateAlertRule for application/json ContentType.
type CreateAlertRuleJSONRequestBody = AlertRuleRequest

// UpdateAlertRuleJSONRequestBody defines body for UpdateAlertRule for application/json ContentType.
type UpdateAlertRuleJSONRequestBody = AlertRuleRequest

// HandleAlertWebhookJSONRequestBody defines body for HandleAlertWebhook for application/json ContentType.
type HandleAlertWebhookJSONRequestBody = AlertWebhookRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create alert rule
	// (POST /api/v1alpha1/alerts/sources/{sourceType}/rules)
	CreateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string)
	// Delete alert rule
	// (DELETE /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	DeleteAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Get alert rule
	// (GET /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	GetAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Update alert rule
	// (PUT /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	UpdateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Handles triggered alerts from the alerting backend
	// (POST /api/v1alpha1/alerts/webhook)
	HandleAlertWebhook(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAlertRule operation middleware
func (siw *ServerInterfaceWrapper) CreateAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAlertRule(w, r, sourceType)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAlertRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlertRule operation middleware
func (siw *ServerInterfaceWrapper) GetAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAlertRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleAlertWebhook operation middleware
func (siw *ServerInterfaceWrapper) HandleAlertWebhook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleAlertWebhook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules", wrapper.CreateAlertRule)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.DeleteAlertRule)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.GetAlertRule)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.UpdateAlertRule)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1alpha1/alerts/webhook", wrapper.HandleAlertWebhook)

	return m
}

type CreateAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	Body       *CreateAlertRuleJSONRequestBody
}

type CreateAlertRuleResponseObject interface {
	VisitCreateAlertRuleResponse(w http.ResponseWriter) error
}

type CreateAlertRule201JSONResponse AlertingRuleSyncResponse

func (response CreateAlertRule201JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule400JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule400JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule409JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule409JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule500JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule500JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
}

type DeleteAlertRuleResponseObject interface {
	VisitDeleteAlertRuleResponse(w http.ResponseWriter) error
}

type DeleteAlertRule200JSONResponse AlertingRuleSyncResponse

func (response DeleteAlertRule200JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule400JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule400JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule404JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule404JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule500JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule500JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
}

type GetAlertRuleResponseObject interface {
	VisitGetAlertRuleResponse(w http.ResponseWriter) error
}

type GetAlertRule200JSONResponse AlertRuleResponse

func (response GetAlertRule200JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule400JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule400JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule404JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule404JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule500JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule500JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
	Body       *UpdateAlertRuleJSONRequestBody
}

type UpdateAlertRuleResponseObject interface {
	VisitUpdateAlertRuleResponse(w http.ResponseWriter) error
}

type UpdateAlertRule200JSONResponse AlertingRuleSyncResponse

func (response UpdateAlertRule200JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule400JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule400JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule404JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule404JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule500JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule500JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhookRequestObject struct {
	Body *HandleAlertWebhookJSONRequestBody
}

type HandleAlertWebhookResponseObject interface {
	VisitHandleAlertWebhookResponse(w http.ResponseWriter) error
}

type HandleAlertWebhook200JSONResponse AlertWebhookResponse

func (response HandleAlertWebhook200JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhook400JSONResponse externalRef0.ErrorResponse

func (response HandleAlertWebhook400JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhook500JSONResponse externalRef0.ErrorResponse

func (response HandleAlertWebhook500JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create alert rule
	// (POST /api/v1alpha1/alerts/sources/{sourceType}/rules)
	CreateAlertRule(ctx context.Context, request CreateAlertRuleRequestObject) (CreateAlertRuleResponseObject, error)
	// Delete alert rule
	// (DELETE /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	DeleteAlertRule(ctx context.Context, request DeleteAlertRuleRequestObject) (DeleteAlertRuleResponseObject, error)
	// Get alert rule
	// (GET /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	GetAlertRule(ctx context.Context, request GetAlertRuleRequestObject) (GetAlertRuleResponseObject, error)
	// Update alert rule
	// (PUT /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	UpdateAlertRule(ctx context.Context, request UpdateAlertRuleRequestObject) (UpdateAlertRuleResponseObject, error)
	// Handles triggered alerts from the alerting backend
	// (POST /api/v1alpha1/alerts/webhook)
	HandleAlertWebhook(ctx context.Context, request HandleAlertWebhookRequestObject) (HandleAlertWebhookResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateAlertRule operation middleware
func (sh *strictHandler) CreateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string) {
	var request CreateAlertRuleRequestObject

	request.SourceType = sourceType

	var body CreateAlertRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAlertRule(ctx, request.(CreateAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAlertRuleResponseObject); ok {
		if err := validResponse.VisitCreateAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAlertRule operation middleware
func (sh *strictHandler) DeleteAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request DeleteAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAlertRule(ctx, request.(DeleteAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAlertRuleResponseObject); ok {
		if err := validResponse.VisitDeleteAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAlertRule operation middleware
func (sh *strictHandler) GetAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request GetAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAlertRule(ctx, request.(GetAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAlertRuleResponseObject); ok {
		if err := validResponse.VisitGetAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAlertRule operation middleware
func (sh *strictHandler) UpdateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request UpdateAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	var body UpdateAlertRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAlertRule(ctx, request.(UpdateAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAlertRuleResponseObject); ok {
		if err := validResponse.VisitUpdateAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleAlertWebhook operation middleware
func (sh *strictHandler) HandleAlertWebhook(w http.ResponseWriter, r *http.Request) {
	var request HandleAlertWebhookRequestObject

	var body HandleAlertWebhookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleAlertWebhook(ctx, request.(HandleAlertWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleAlertWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleAlertWebhookResponseObject); ok {
		if err := validResponse.VisitHandleAlertWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ3VPcOBL/V7p8VwWk5gOye1V788aS3C61OUgFsvuQSYUeq8fWRpYcSWbwpfjfr1qy",
	"ZzyMhwCVPVI5XsAjyf356y/5c5KaojSatHfJ5HPi0pwKDI+Hiqx/Uyl6Q58qcp7XSmtKsl5SOJEaLaSX",
	"Rm9ukcaZIsGPglxqZRnPJX/k5HOy4HMCZA5gK0UgHbSvDBJfl5RMkpkxilAn14NEak/2EtUmvfOcoN0F",
	"MwcvCwJv4FNFtoa5uclpRd55K3XG1Flw9Mb2U293mWrlqJ8m6apIJu+SzCeDJPO8pHz4E3Y/JYNE06fk",
	"fQ93n1tyuVGin/1yGy5RVXSrFA1tXRUzskx7IbUwi37Cce9hNrseJJY+VdKyi98lK9c1DDse65i3q+vK",
	"Emb2J6WepS3Io0CPfUhrQPpWbjHTaUn6KDeWDCwPw9vjF0u9kkEyN7ZAn0ySqpKiDwikL6U1urgjo87x",
	"e7PSWFA/A94JXvkibvmkKzG9hVDY3qQGR2/6CJbWsC/uontz9J5638BNMEJXjzURNvwxWMdBH4ScqWy0",
	"xzqACvJWpv1axb31AGjWZuhIRLu5TpSnZfWhcpixwAUVxtbLn7NKZOR7Az3aqFeEyNgboCtKKx/DW5ns",
	"pgCbySMs9OaNulw6vrHKSgFlsiB6MMotQt/wV9jdNPuNU8swXrpj0CkVfV7rlBpXGu3oqdY81ZoOBp8q",
	"xf9jpXhK7n95ct9M5P25+Q+a5cZ83DoJBB3OZUHOY1FukbndXgNZFwkCPQ35WJ8xwunfOS31k48Z6wbp",
	"jSTFkD75CgHV0nlYUN0N7uuW31YYC3IBnVvQHzbXJVhEkn1qOY++cv204t42Ui34XJWm5EI8WWvsnWDX",
	"qCp1xj3AWa3T7epi2jYBmxLGPfD4kTTww7bKmVpCH8p/VYr2Sac56iw8C1LEq32BrtB5FpHEob8j0PkV",
	"cLVOtyHpZ0w/khbHW5LpLG7D8QvY5Sw6t6YAM3PciMykkr5uj+zdHb2vTCZTVNt4qrgdeDKS70j5vgC6",
	"4RgXDMs5AaXqdUAfeqIpyA6xlB9eMuy24yeg8siILQETtiE1grpWJgv8T8Y0e4VFqViC05/Phr8fDF8N",
	"nz/vs8XWyPy1KlAPLaHgLrTh2Z7uMvi3dE7qDNruGuaSlHCw4zzGfLsDqAXskBbhV28VkV7dqm2Hc+OG",
	"GYo21XNgYOVzY+V/omeMnUkhSHObafy/TKXjZKbnSqa+Hf01qrNgueCPePaY1eIe6I6evQ7d+Nw0/b/H",
	"NERcbIiSTotxTliwqrf2IaetK48b+eDw9TEPA2FZtAmj9fiOg1aRqS6N9bB7fHL+8s3J4asPr0/fnA9A",
	"0Bwr5eGn/Z8O9oIf6Ko0LpBSNaADhFRVzpMdKpMynaP48/g1nEU8we4SvC23vREce5br5PQcrKk8CW7M",
	"TZXlLOBUZ+hpgXXg2B4jTPMApojayjspKOjTSDCa6qk+QqXIOkDLg8yw2Vq1wW4A2njgXFM5sm4y1QDD",
	"jlnadFMq1LTjGps2q8spDthZ1jAv2F1rJd++2IskUd+gWBhRKSapTOaGKLBkyZbN2mppd63y7LFah5XP",
	"SXuZInt+Aj6XLjhXUKrQkgNtwFFaWeYUrjhpADNKkacbbTTPhFNNem5sSmIEJ+QXxn5szRollC7aM+o2",
	"gnPmgmlaWfSkaojgm5Gbaj4nqFSmZt+Z0iiT1WCxmUZRs/7oSmmDxDAcgqPoLm08wYyUWQSPPXt2qgno",
	"qkGsoJK0IJ3Wo2fPogSupBTMQjuQ3vEDCFOg1NBc5bKgNNWcRzjXXKUU4oPVuVjLlRcDWOQyzXknI11J",
	"zVq5HDnxLKRv0FdWMyXTYN4GgBd/tzS/2BERexfdbDyqsVAX4EzQ7RfDbibFlaB2rUzD2MAKFhQ9sDcs",
	"zcmSTrmBQR3tPpcMLNQM0BnXJxQkgN1uSdVTzSpFA0wANffbRrGtPXtRsHWYrRaomMNwCAjCpA6CPi4f",
	"AE4129JbVGNLwqSqBiW1HzCerBiWaH0NZy9+Y+vQynNF5ZiHM+qSpvpiNO4xQLBMaNa5wxTSUuqNrUfw",
	"G1EJM+PzoJ8Db7J4ZyH1VF+YkjSWcnwxCLaeVVqoAJMCdmmUjeCiFTRuXezBjObGEuSoBVcODoWoFw8g",
	"qGufx2X0rTHnRimzAEsKvbxsDG1p7kZTzvFKptRU0ibxHpaY5gTPR/tcHaxKJknufekm4/FisRhh2B4Z",
	"m42bd9341fHRy5Ozl8Pno/1R7gvVqUvJl1J0MkguybqY0w9G+6P95h6FTZNMkh9G+6MfkkFSos9DiR+z",
	"yS4PUJU5HozjeDWOIHPjz/HhvC7pesxZKbxSosWCPFmXTN719i7hrbW5q5PYdpXJBk2mGnDSijPXXiiG",
	"ySSIlrSTfLKSIOlenHlb0aD5ABOvte45zr0fJKVxPU3pUWh3Q87p3IKtl7tOgxMvoaTR3Bs2Ly9zeyMy",
	"Of+zEXVbmUkHtliWqsnC4z9dbNNXCnGaSCbJ38arejNuktR442PT9fqtIhsnLMRcFZz2fP/g6/LvG0CC",
	"HOvmPFwZsRkkoJl65pVSNaPzx/39rybaLd1tj3DH+hKVFGBbO7Iw/3wkYTqWQsVpuAa6ks47Fusfj2ij",
	"JrvEDhVii8rnXFUUaOtOzKxNO5hxfohqueQ9v3HPZDP+3N4cXMc45UFzM2JfhPUHRmx8eT1i18Jm/7HD",
	"ppmvv/Ww+fHxwyYWaB6xvvmIaTF7a8QMEi5eG3j/hfwDwf4L+f8d0tc+Ud3uOMv1mi6fQP59gTwA9QsI",
	"/y6aycG97sd7BFvetN8mVl8LW/Xkh7fhmvaBKSK+/G12sI9eipsL8Kcs9T1lqTZcHtS8tt90eCzuHSd/",
	"RS3CXYWVWUZ2+QlzdcuBDRbbzxIbIRlJdD9w/ZVReePr5WME5s3PeFuh1lg/XOCobz0uv+0oeBBON8Pk",
	"ern4eZsQN+64w2Xd2jU1kBalkTp852+v0SKH6/fX/w0AAP//p6Nb/4UrAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./observer-api.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
