//go:build go1.22

// Package internalgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package internalgen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	externalRef0 "github.com/openchoreo/openchoreo/internal/observer/api/gen"
)

// CreateAlertRuleJSONRequestBody defines body for CreateAlertRule for application/json ContentType.
type CreateAlertRuleJSONRequestBody = externalRef0.AlertRuleRequest

// UpdateAlertRuleJSONRequestBody defines body for UpdateAlertRule for application/json ContentType.
type UpdateAlertRuleJSONRequestBody = externalRef0.AlertRuleRequest

// HandleAlertWebhookJSONRequestBody defines body for HandleAlertWebhook for application/json ContentType.
type HandleAlertWebhookJSONRequestBody = externalRef0.AlertWebhookRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create alert rule
	// (POST /api/v1alpha1/alerts/sources/{sourceType}/rules)
	CreateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string)
	// Delete alert rule
	// (DELETE /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	DeleteAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Get alert rule
	// (GET /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	GetAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Update alert rule
	// (PUT /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	UpdateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Handles triggered alerts from the alerting backend
	// (POST /api/v1alpha1/alerts/webhook)
	HandleAlertWebhook(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAlertRule operation middleware
func (siw *ServerInterfaceWrapper) CreateAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAlertRule(w, r, sourceType)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAlertRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlertRule operation middleware
func (siw *ServerInterfaceWrapper) GetAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAlertRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleAlertWebhook operation middleware
func (siw *ServerInterfaceWrapper) HandleAlertWebhook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleAlertWebhook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules", wrapper.CreateAlertRule)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.DeleteAlertRule)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.GetAlertRule)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.UpdateAlertRule)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1alpha1/alerts/webhook", wrapper.HandleAlertWebhook)

	return m
}

type CreateAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	Body       *CreateAlertRuleJSONRequestBody
}

type CreateAlertRuleResponseObject interface {
	VisitCreateAlertRuleResponse(w http.ResponseWriter) error
}

type CreateAlertRule201JSONResponse externalRef0.AlertingRuleSyncResponse

func (response CreateAlertRule201JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule400JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule400JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule409JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule409JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule500JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule500JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
}

type DeleteAlertRuleResponseObject interface {
	VisitDeleteAlertRuleResponse(w http.ResponseWriter) error
}

type DeleteAlertRule200JSONResponse externalRef0.AlertingRuleSyncResponse

func (response DeleteAlertRule200JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule400JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule400JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule404JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule404JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule500JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule500JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
}

type GetAlertRuleResponseObject interface {
	VisitGetAlertRuleResponse(w http.ResponseWriter) error
}

type GetAlertRule200JSONResponse externalRef0.AlertRuleResponse

func (response GetAlertRule200JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule400JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule400JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule404JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule404JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule500JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule500JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
	Body       *UpdateAlertRuleJSONRequestBody
}

type UpdateAlertRuleResponseObject interface {
	VisitUpdateAlertRuleResponse(w http.ResponseWriter) error
}

type UpdateAlertRule200JSONResponse externalRef0.AlertingRuleSyncResponse

func (response UpdateAlertRule200JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule400JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule400JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule404JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule404JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule500JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule500JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhookRequestObject struct {
	Body *HandleAlertWebhookJSONRequestBody
}

type HandleAlertWebhookResponseObject interface {
	VisitHandleAlertWebhookResponse(w http.ResponseWriter) error
}

type HandleAlertWebhook200JSONResponse externalRef0.AlertWebhookResponse

func (response HandleAlertWebhook200JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhook400JSONResponse externalRef0.ErrorResponse

func (response HandleAlertWebhook400JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhook500JSONResponse externalRef0.ErrorResponse

func (response HandleAlertWebhook500JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create alert rule
	// (POST /api/v1alpha1/alerts/sources/{sourceType}/rules)
	CreateAlertRule(ctx context.Context, request CreateAlertRuleRequestObject) (CreateAlertRuleResponseObject, error)
	// Delete alert rule
	// (DELETE /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	DeleteAlertRule(ctx context.Context, request DeleteAlertRuleRequestObject) (DeleteAlertRuleResponseObject, error)
	// Get alert rule
	// (GET /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	GetAlertRule(ctx context.Context, request GetAlertRuleRequestObject) (GetAlertRuleResponseObject, error)
	// Update alert rule
	// (PUT /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	UpdateAlertRule(ctx context.Context, request UpdateAlertRuleRequestObject) (UpdateAlertRuleResponseObject, error)
	// Handles triggered alerts from the alerting backend
	// (POST /api/v1alpha1/alerts/webhook)
	HandleAlertWebhook(ctx context.Context, request HandleAlertWebhookRequestObject) (HandleAlertWebhookResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateAlertRule operation middleware
func (sh *strictHandler) CreateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string) {
	var request CreateAlertRuleRequestObject

	request.SourceType = sourceType

	var body CreateAlertRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAlertRule(ctx, request.(CreateAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAlertRuleResponseObject); ok {
		if err := validResponse.VisitCreateAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAlertRule operation middleware
func (sh *strictHandler) DeleteAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request DeleteAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAlertRule(ctx, request.(DeleteAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAlertRuleResponseObject); ok {
		if err := validResponse.VisitDeleteAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAlertRule operation middleware
func (sh *strictHandler) GetAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request GetAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAlertRule(ctx, request.(GetAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAlertRuleResponseObject); ok {
		if err := validResponse.VisitGetAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAlertRule operation middleware
func (sh *strictHandler) UpdateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request UpdateAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	var body UpdateAlertRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAlertRule(ctx, request.(UpdateAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAlertRuleResponseObject); ok {
		if err := validResponse.VisitUpdateAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleAlertWebhook operation middleware
func (sh *strictHandler) HandleAlertWebhook(w http.ResponseWriter, r *http.Request) {
	var request HandleAlertWebhookRequestObject

	var body HandleAlertWebhookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleAlertWebhook(ctx, request.(HandleAlertWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleAlertWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleAlertWebhookResponseObject); ok {
		if err := validResponse.VisitHandleAlertWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bRhL+KwPeAbEDirLTHtDTN9fJtUZzThE77YcqiEfcEbnNcpfZXVrRBf7vh9kl",
	"ZUqiHNu4XHw5A0Urc5ezszPPPPPCfkpyU9VGk/YumXxKXF5SheGnmTmyl2RHWMt3R4qsf90oek0fGnKe",
	"N9TW1GS9pLA9N1pIL43eXiKNM0WCfwpyuZV13Jf8XpIvyYIvCZBPANsoAumgeyVN/LKmZJLMjFGEOrlK",
	"E6k92UtU2/LOS4JuFcwcvKwIvIEPDdklzM3mSdfinbdSFyydFUdv7LD0bpWlNo6GZZJuqmTyR1L4JE0K",
	"z4+UD/8Kqx+SNNH0IXk7cLovLbnSKDF8/GoZLlE1dKMWrWzdVDOyLHshtTCLYcFx7X42u0oTSx8aadnF",
	"fyTXrmsP7HmsZ97+Xa8tYWZ/Uu5Z24o8CvQ4hLQWsW/kDjO9qkkfl8aSgdVmeHPyfHWvJE3mxlbok0nS",
	"NFIMAYH0pbRGV7c8qLf9zkdprGj4AF4JXvksbnmnqzG/QVBY3pYGx6+HBNbWsC9uc/d26x3vvYGbYIT+",
	"PdZU2PJHuo6DIQg509hoj3UAVeStzIdvFdfWA6B9NkNHItrN9aI8r5t3jcOCFa6oMna5+nPWiIL8YKBH",
	"Gw2qEA/2Bugj5Y2P4a1MsanANnmEB4O8saxXjm+tcn0BZYqgejDKDUpv+Cusbpt9Y9cqjFfuSHupYshr",
	"u/KOq4129Jh4HhNPD5CPaeP/MW08Mv0XZ/ptVr8FUf9Os9KY9zt7hHChc1mR81jVOy7QLa8hrg8LgZ5G",
	"vG3IMmH3b8xRw+IjfW2I3mIsxvfpfyC6Ojn3i7DbYf8GN+xKmRW5gNsdcREW19VZRJFDd3QefeOGZcW1",
	"XaI6WLomz8mFSLPW2FsBcujeUhdcKpwtdb777ph3tcK2unENPL4nDfxjV4LNLaEPVUJTi+6XzkvURfgt",
	"SBE/HeIDhc6ziiSO/C1DgF8Bt9T5Loz9iPl70uJkB+fO4jKcPIc9Jtu5NRVE++FMKumX3Zb92+P6pSlk",
	"jmrXmSouhzMZ47eUfFc0bTjGBcMyW6BUgw74LJReMAZ34ydA9NiIHdETliE3gvpWJgv8HxnZ+CNWtWIN",
	"Xv14NvrtcPRy9OzZkC12hunPTYV6ZAkFF6vtmd3u/gH/lM5JXUBXkcNckhIOnjiPkYmfAGoBT0iL8Ndg",
	"spFe3Xjb3smtG2YouiTAgYGNL42V/4qeMXYmhSDN1ajx/zCNjt2cniuZ+25coFGdBcsFf8S9J3wtLpVu",
	"6dmrULTPTdsmeMxDxMW6KelVIueEFV/1xnLlVefKk1Y/OPr1hHuG8Fh0hNF5/ImD7iJTXRvrYe/k9PzF",
	"69Ojl+9+ffX6PAVBc2yUhx8OfjjcD36gj7VxQZRaAjpAyFXjPNmRMjnLOY5/nvwKZxFPsLcCb3fafgYn",
	"nvU6fXUO1jSeBNfvpilKVnCqC/S0wGU4sdtGmJcBTBG1jXdSULhPq0E21VN9jEqRdYCW+51Ru3RdLbsU",
	"tPHAXNM4sm4y1QCjKMZob42CWqGmJ661Zks/qzav26bIwt5arfnm+f61MGzpfsVse2u5ZZ91PWp8SdrL",
	"HNmdE/CldMFjgnKFlhxoA47yxjL/hcEnpTCjHLmz0UZzPzjVpOfG5iQyOCW/MPZ9Z6vIm9L1b5fBOZ+C",
	"ed5Y9KSWEBE1IzfVvE9QrcySHWJqo0yxBIttJ4oa+B9XSxs0htEIHEUfaOMJZqTMIrjh6dNT48GRmo8C",
	"rKUmkT19Ci8uuZ6MM1woyYaOFjXQxxawF3+1NL9gXJqpvujTXrbESl2ksChlXsJ7otqBK5E5g4PKwd7m",
	"CDid6jWqTCHLsn1gvlE0irWnCBirCHU0008GKiNIRQRp46daNLViH7GFQ/KzKGhk5vNoWvTRcXPJ4EDN",
	"8JpxdkERQ056B2ahJ1ONmmtpo+JbzI4OpOesoQUq9udoBAjC5A7qZqakK1NAcDXl3qIaWxImV8upVlL7",
	"lI+1YlSj9Us4e/4LFKTp2jNV4/gMZ9QlwUU23rblVIdQCoU4F4xCWsq9scsMfiGqYWZ8Ga7lwJsiziOk",
	"hgtTk8Zaji9SNt5UzxotVIBBBXuUFRlctJpCXLrYhxnNjSUoUQuOimAxvhf3FqiXvpS6YACi72w4N0qZ",
	"BVhS6OUlRftamrtsysSsZE5t+mvZ8qjGvCR4lh0wpVuVTJLS+9pNxuPFYpFhWM6MLcbtu2788uT4xenZ",
	"i9Gz7CArfaV6yST5HK8maXJJ1kUiPswOsoN2RsK2SSbJd9lB9l2SJjX6MuTlMdvs8hBVXeLhOLZO44hC",
	"N/4Uf5wva7oaM6GEV2q0WJEn65LJH4MFR3hrrafqcdKeMkXatowpGAuxn9oPGSyZBNWSrktPrjVI+hMy",
	"bxtK288ucWR1x1btbZrUxg1UksehRg2c0ptwreeoXlUSB0zSaC7o2pdXId+qTM7/aMSyS6ekw7FYxwiW",
	"Ro//dLG2vr4QM04ySf4yvk4S4/Yr0/jmT0xX67NEtlR4EOkmePDZweEXVGaonwhKrRv66Nq8bV8AbUcz",
	"b5RaMm6/Pzj4MnquF6sDyp3oS1RSgO2Mysr8/Ssp07MUKiboJdBH6bxjtf72FW3U8k4sOCFWnLzPNVWF",
	"dtmLprXmBQtmjngtl7zlN+5IQ+NP3YjgKkYw943bsfw8PL9nLMeX12N5LYYOHlQMtb3zQ4+h779+DMU8",
	"zu3Tgw+fDsA3hk+acI7bAv9P5O+J/J/IfyXYr32yutmLlnM8XT4i/ttCfEDtZ+D+TRSg6Z1G5AOKrYbt",
	"N6k1VPY2A2TxJsxj78kX8eX/gar3YWXsdgb+yF/fEn91gXSvgrf7xsNN9mBz+jNqESYfVhYF2dXHTljN",
	"TDZHfFvBGkX0P3j91+J14zvnVw/ZzQ9+O0HY+iUMitRDj9iHHR/3QvB2AF2tHn7apcTGGDyMVNfG3UBa",
	"1Ebq8P8KdOO6eMLV26t/BwAA///8MgOZ4ysAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./observer-api.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
