{{ if .Values.global.defaultResources.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: docker
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
  labels:
    {{- include "openchoreo-build-plane.labels" . | nindent 4 }}
spec:
  entrypoint: build-workflow
  arguments:
    parameters:
      - name: docker-context
      - name: dockerfile-path
  templates:
    - name: build-workflow
      steps:
        - - name: clone-step
            template: clone-step
        - - name: build-step
            template: build-step
            arguments:
              parameters:
                - name: git-revision
                  value: '{{ "{{" }}steps.clone-step.outputs.parameters.git-revision{{ "}}" }}'
        - - name: push-step
            template: push-step
            arguments:
              parameters:
                - name: git-revision
                  value: '{{ "{{" }}steps.clone-step.outputs.parameters.git-revision{{ "}}" }}'
        - - name: workload-create-step
            template: workload-create-step
            arguments:
              parameters:
                - name: image
                  value: '{{ "{{" }}steps.push-step.outputs.parameters.image{{ "}}" }}'
    - name: clone-step
      outputs:
        parameters:
          - name: git-revision
            valueFrom:
              path: /tmp/git-revision.txt
      container:
        args:
          - |-
            set -e

            BRANCH={{ "{{" }}workflow.parameters.branch{{ "}}" }}
            REPO={{ "{{" }}workflow.parameters.git-repo{{ "}}" }}
            COMMIT={{ "{{" }}workflow.parameters.commit{{ "}}" }}

            if [[ -n "$COMMIT" ]]; then
                echo "Cloning specific commit: $COMMIT"
                git clone --no-checkout --depth 1 "$REPO" /mnt/vol/source
                cd /mnt/vol/source
                git config --global advice.detachedHead false
                git fetch --depth 1 origin "$COMMIT"
                git checkout "$COMMIT"
                echo -n "$COMMIT" | cut -c1-8 > /tmp/git-revision.txt
            else
                echo "Cloning branch: $BRANCH with latest commit"
                git clone --single-branch --branch $BRANCH --depth 1 "$REPO" /mnt/vol/source
                cd /mnt/vol/source
                COMMIT_SHA=$(git rev-parse HEAD)
                echo -n "$COMMIT_SHA" | cut -c1-8 > /tmp/git-revision.txt
            fi
        command:
          - sh
          - -c
        image: alpine/git
        name: ""
        volumeMounts:
          - mountPath: /mnt/vol
            name: workspace
    - name: build-step
      inputs:
        parameters:
          - name: git-revision
      container:
        args:
          - |-
            set -e

            WORKDIR=/mnt/vol/source
            IMAGE="{{ "{{" }}workflow.parameters.image-name{{ "}}" }}:{{ "{{" }}workflow.parameters.image-tag{{ "}}" }}-{{ "{{" }}inputs.parameters.git-revision{{ "}}" }}"
            DOCKER_CONTEXT="{{ "{{" }}workflow.parameters.docker-context{{ "}}" }}"
            DOCKERFILE_PATH="{{ "{{" }}workflow.parameters.dockerfile-path{{ "}}" }}"

            #####################################################################
            # 1.  Podman daemon + storage.conf
            #####################################################################
            mkdir -p /etc/containers
            cat > /etc/containers/storage.conf <<EOF
            [storage]
            driver = "overlay"
            runroot = "/run/containers/storage"
            graphroot = "/var/lib/containers/storage"
            [storage.options.overlay]
            mount_program = "/usr/bin/fuse-overlayfs"
            EOF

            #####################################################################
            # 2.  Docker Build
            #####################################################################
            podman build -t $IMAGE -f $WORKDIR/$DOCKERFILE_PATH $WORKDIR/$DOCKER_CONTEXT
            podman save -o /mnt/vol/app-image.tar $IMAGE
        command:
          - sh
          - -c
        image: ghcr.io/openchoreo/podman-runner:v1.0
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /mnt/vol
            name: workspace
          - mountPath: /shared/podman/cache
            name: podman-cache
    - name: push-step
      inputs:
        parameters:
          - name: git-revision
      outputs:
        parameters:
          - name: image
            valueFrom:
              path: /tmp/image.txt
      container:
        args:
          - |-
            set -e
            #####################################################################
            # 1. Inputs
            #####################################################################
            GIT_REVISION={{ "{{" }}inputs.parameters.git-revision{{ "}}" }}
            IMAGE_NAME={{ "{{" }}workflow.parameters.image-name{{ "}}" }}
            IMAGE_TAG={{ "{{" }}workflow.parameters.image-tag{{ "}}" }}
            SRC_IMAGE="${IMAGE_NAME}:${IMAGE_TAG}-${GIT_REVISION}"

            #####################################################################
            # 2. Registry endpoints from Helm values
            #    - type: "local" or "external"
            #    - choose the right push/pull endpoints
            #####################################################################
            REGISTRY_TYPE="{{ .Values.global.defaultResources.registry.type | default "local" }}"

            if [ "${REGISTRY_TYPE}" = "local" ]; then
              REGISTRY_PULL="{{ .Values.global.defaultResources.registry.local.pullEndpoint }}"
              REGISTRY_PUSH="{{ .Values.global.defaultResources.registry.local.pushEndpoint }}"
            else
              REGISTRY_PULL="{{ .Values.global.defaultResources.registry.external.endpoint }}"
              REGISTRY_PUSH="{{ .Values.global.defaultResources.registry.external.endpoint }}"
            fi

            #####################################################################
            # 3. Podman storage configuration
            #####################################################################
            mkdir -p /etc/containers
            cat <<EOF > /etc/containers/storage.conf
            [storage]
            driver = "overlay"
            runroot = "/run/containers/storage"
            graphroot = "/var/lib/containers/storage"
            [storage.options.overlay]
            mount_program = "/usr/bin/fuse-overlayfs"
            EOF

            #####################################################################
            # 4. Load the tarred image and push to the selected registry
            #####################################################################
            podman load -i /mnt/vol/app-image.tar

            podman tag $SRC_IMAGE $REGISTRY_PUSH/$SRC_IMAGE
            podman push --tls-verify=false $REGISTRY_PUSH/$SRC_IMAGE

            #####################################################################
            # 5. Emit image reference (for later steps/kubelet pulls)
            #####################################################################
            echo -n "$REGISTRY_PULL/$SRC_IMAGE" > /tmp/image.txt
        command:
          - sh
          - -c
        image: ghcr.io/openchoreo/podman-runner:v1.0
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /mnt/vol
            name: workspace
    - name: workload-create-step
      inputs:
        parameters:
          - name: image
      outputs:
        parameters:
          - name: workload-cr
            valueFrom:
              path: /mnt/vol/workload-cr.yaml
      container:
        image: ghcr.io/openchoreo/podman-runner:v1.0
        command: [ sh, -c ]
        args:
          - |-
            set -e

            #####################################################################
            # 1. Initialize variables
            #####################################################################
            IMAGE={{ "{{" }}inputs.parameters.image{{ "}}" }}
            PROJECT_NAME={{ "{{" }}workflow.parameters.project-name{{ "}}" }}
            COMPONENT_NAME={{ "{{" }}workflow.parameters.component-name{{ "}}" }}
            APP_PATH="{{ "{{" }}workflow.parameters.app-path{{ "}}" }}"

            DESCRIPTOR_PATH="/mnt/vol/source${APP_PATH:+/${APP_PATH#/}}"

            OUTPUT_PATH="/mnt/vol/workload-cr.yaml"

            echo "Creating workload with image: ${IMAGE}"
            echo "Using descriptor in: ${DESCRIPTOR_PATH}"

            #####################################################################
            # 2. Podman storage configuration
            #####################################################################
            mkdir -p /etc/containers
            cat <<EOF > /etc/containers/storage.conf
            [storage]
            driver = "overlay"
            runroot = "/run/containers/storage"
            graphroot = "/var/lib/containers/storage"
            [storage.options.overlay]
            mount_program = "/usr/bin/fuse-overlayfs"
            EOF

            #####################################################################
            # 3. Create workload CR and export to output
            #####################################################################
            podman run --rm --network=none \
            -v $DESCRIPTOR_PATH:/app:rw -w /app \
            ghcr.io/openchoreo/openchoreo-cli:{{ .Chart.AppVersion }} \
              create workload \
              --project "${PROJECT_NAME}" \
              --component "${COMPONENT_NAME}" \
              --image "${IMAGE}" \
              --descriptor "workload.yaml" \
              -o "workload-cr.yaml"

            # Copy output CR to the shared volume
            cp -f "${DESCRIPTOR_PATH}/workload-cr.yaml" "${OUTPUT_PATH}"
        volumeMounts:
          - name: workspace
            mountPath: /mnt/vol
        securityContext:
          privileged: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: openchoreo.dev/noderole
                operator: In
                values:
                  - workflow-runner
  ttlStrategy:
    secondsAfterFailure: 3600
    secondsAfterSuccess: 3600
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  volumes:
    - hostPath:
        path: /shared/podman/cache
        type: DirectoryOrCreate
      name: podman-cache
{{ end }}
