// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateHook provides a mock function with given fields: ctx, namespaceName, h
func (_m *MockService) CreateHook(ctx context.Context, namespaceName string, h *v1alpha1.Hook) (*v1alpha1.Hook, error) {
	ret := _m.Called(ctx, namespaceName, h)

	if len(ret) == 0 {
		panic("no return value specified for CreateHook")
	}

	var r0 *v1alpha1.Hook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Hook) (*v1alpha1.Hook, error)); ok {
		return rf(ctx, namespaceName, h)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Hook) *v1alpha1.Hook); ok {
		r0 = rf(ctx, namespaceName, h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Hook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Hook) error); ok {
		r1 = rf(ctx, namespaceName, h)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHook'
type MockService_CreateHook_Call struct {
	*mock.Call
}

// CreateHook is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - h *v1alpha1.Hook
func (_e *MockService_Expecter) CreateHook(ctx interface{}, namespaceName interface{}, h interface{}) *MockService_CreateHook_Call {
	return &MockService_CreateHook_Call{Call: _e.mock.On("CreateHook", ctx, namespaceName, h)}
}

func (_c *MockService_CreateHook_Call) Run(run func(ctx context.Context, namespaceName string, h *v1alpha1.Hook)) *MockService_CreateHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Hook))
	})
	return _c
}

func (_c *MockService_CreateHook_Call) Return(_a0 *v1alpha1.Hook, _a1 error) *MockService_CreateHook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateHook_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Hook) (*v1alpha1.Hook, error)) *MockService_CreateHook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHook provides a mock function with given fields: ctx, namespaceName, hookName
func (_m *MockService) DeleteHook(ctx context.Context, namespaceName string, hookName string) error {
	ret := _m.Called(ctx, namespaceName, hookName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, hookName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHook'
type MockService_DeleteHook_Call struct {
	*mock.Call
}

// DeleteHook is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - hookName string
func (_e *MockService_Expecter) DeleteHook(ctx interface{}, namespaceName interface{}, hookName interface{}) *MockService_DeleteHook_Call {
	return &MockService_DeleteHook_Call{Call: _e.mock.On("DeleteHook", ctx, namespaceName, hookName)}
}

func (_c *MockService_DeleteHook_Call) Run(run func(ctx context.Context, namespaceName string, hookName string)) *MockService_DeleteHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteHook_Call) Return(_a0 error) *MockService_DeleteHook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteHook_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteHook_Call {
	_c.Call.Return(run)
	return _c
}

// GetHook provides a mock function with given fields: ctx, namespaceName, hookName
func (_m *MockService) GetHook(ctx context.Context, namespaceName string, hookName string) (*v1alpha1.Hook, error) {
	ret := _m.Called(ctx, namespaceName, hookName)

	if len(ret) == 0 {
		panic("no return value specified for GetHook")
	}

	var r0 *v1alpha1.Hook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Hook, error)); ok {
		return rf(ctx, namespaceName, hookName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Hook); ok {
		r0 = rf(ctx, namespaceName, hookName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Hook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, hookName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHook'
type MockService_GetHook_Call struct {
	*mock.Call
}

// GetHook is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - hookName string
func (_e *MockService_Expecter) GetHook(ctx interface{}, namespaceName interface{}, hookName interface{}) *MockService_GetHook_Call {
	return &MockService_GetHook_Call{Call: _e.mock.On("GetHook", ctx, namespaceName, hookName)}
}

func (_c *MockService_GetHook_Call) Run(run func(ctx context.Context, namespaceName string, hookName string)) *MockService_GetHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetHook_Call) Return(_a0 *v1alpha1.Hook, _a1 error) *MockService_GetHook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetHook_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.Hook, error)) *MockService_GetHook_Call {
	_c.Call.Return(run)
	return _c
}

// ListHooks provides a mock function with given fields: ctx, namespaceName, opts
func (_m *MockService) ListHooks(ctx context.Context, namespaceName string, opts services.ListOptions) (*services.ListResult[v1alpha1.Hook], error) {
	ret := _m.Called(ctx, namespaceName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListHooks")
	}

	var r0 *services.ListResult[v1alpha1.Hook]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.Hook], error)); ok {
		return rf(ctx, namespaceName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) *services.ListResult[v1alpha1.Hook]); ok {
		r0 = rf(ctx, namespaceName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.Hook])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListHooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHooks'
type MockService_ListHooks_Call struct {
	*mock.Call
}

// ListHooks is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListHooks(ctx interface{}, namespaceName interface{}, opts interface{}) *MockService_ListHooks_Call {
	return &MockService_ListHooks_Call{Call: _e.mock.On("ListHooks", ctx, namespaceName, opts)}
}

func (_c *MockService_ListHooks_Call) Run(run func(ctx context.Context, namespaceName string, opts services.ListOptions)) *MockService_ListHooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListHooks_Call) Return(_a0 *services.ListResult[v1alpha1.Hook], _a1 error) *MockService_ListHooks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListHooks_Call) RunAndReturn(run func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.Hook], error)) *MockService_ListHooks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHook provides a mock function with given fields: ctx, namespaceName, h
func (_m *MockService) UpdateHook(ctx context.Context, namespaceName string, h *v1alpha1.Hook) (*v1alpha1.Hook, error) {
	ret := _m.Called(ctx, namespaceName, h)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHook")
	}

	var r0 *v1alpha1.Hook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Hook) (*v1alpha1.Hook, error)); ok {
		return rf(ctx, namespaceName, h)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Hook) *v1alpha1.Hook); ok {
		r0 = rf(ctx, namespaceName, h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Hook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Hook) error); ok {
		r1 = rf(ctx, namespaceName, h)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHook'
type MockService_UpdateHook_Call struct {
	*mock.Call
}

// UpdateHook is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - h *v1alpha1.Hook
func (_e *MockService_Expecter) UpdateHook(ctx interface{}, namespaceName interface{}, h interface{}) *MockService_UpdateHook_Call {
	return &MockService_UpdateHook_Call{Call: _e.mock.On("UpdateHook", ctx, namespaceName, h)}
}

func (_c *MockService_UpdateHook_Call) Run(run func(ctx context.Context, namespaceName string, h *v1alpha1.Hook)) *MockService_UpdateHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Hook))
	})
	return _c
}

func (_c *MockService_UpdateHook_Call) Return(_a0 *v1alpha1.Hook, _a1 error) *MockService_UpdateHook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateHook_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Hook) (*v1alpha1.Hook, error)) *MockService_UpdateHook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
