{{- if eq .Values.global.installationMode "standard" }}
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin-credentials-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.openSearchCluster.adminUsername | b64enc }}
  password: {{ .Values.openSearchCluster.adminUserPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-security-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  internal_users.yml: {{- (printf .Values.openSearchCluster.internalUsers (.Values.openSearchCluster.adminUserPassword | bcrypt)) | b64enc | nindent 4 }}
  
{{- end }}
