---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hubble
    app.kubernetes.io/component: hubble
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "openchoreo-observability-plane.chart" . }}
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
      - cilium
  endpoints:
    - port: hubble-metrics
      path: /metrics
      interval: 30s
      metricRelabelings:
        - action: labeldrop
          regex: 'endpoint|job|node|service|container|prometheus|namespace|instance|protocol|method'
