// Copyright 2026 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

// Command auditcoverage generates docs/audit/coverage-matrix.md: every
// audited REST operation and MCP tool, every exemption with its reason,
// which operations supply full resource identity, and known non-events. Run
// via `make audit-coverage-matrix`.
//
// Reporting only — it does not affect what is audited, only what is
// documented about what's audited, so unlike tools/auditgen its output is
// not wired into code.gen-check.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"sort"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	apiaudit "github.com/openchoreo/openchoreo/internal/openchoreo-api/audit"
	"github.com/openchoreo/openchoreo/internal/openchoreo-api/mcphandlers"
	"github.com/openchoreo/openchoreo/internal/openchoreo-api/services/handlerservices"
	"github.com/openchoreo/openchoreo/internal/server/middleware/audit"
	"github.com/openchoreo/openchoreo/pkg/mcp/tools"
)

func main() {
	out := flag.String("out", "docs/audit/coverage-matrix.md", "output file path")
	flag.Parse()

	src, err := render()
	if err != nil {
		log.Fatalf("auditcoverage: %v", err)
	}
	if err := os.WriteFile(*out, []byte(src), 0o600); err != nil {
		log.Fatalf("auditcoverage: failed to write %s: %v", *out, err)
	}
	fmt.Printf("auditcoverage: wrote %s\n", *out)
}

// registerAllToolsets enables every toolset regardless of what a given
// deployment's config turns on, since this document describes what exists in
// code, not one deployment's runtime configuration.
func registerAllToolsets() map[string]tools.ToolPermission {
	handler := mcphandlers.NewMCPHandler(&handlerservices.Services{})
	toolsets := tools.NewToolsets(handler, tools.AllToolsetTypes())
	server := mcp.NewServer(&mcp.Implementation{Name: "auditcoverage", Version: "0.0.0"}, nil)
	perms, _ := toolsets.Register(server)
	return perms
}

func render() (string, error) {
	ops := apiaudit.GetOperations()
	sort.Slice(ops, func(i, j int) bool { return ops[i].ID < ops[j].ID })

	bindings, err := apiaudit.MCPBindings()
	if err != nil {
		return "", fmt.Errorf("apiaudit.MCPBindings: %w", err)
	}

	perms := registerAllToolsets()

	out := "# Audit Coverage Matrix\n\n" +
		"Generated by `tools/auditcoverage` (`make audit-coverage-matrix`). Describes what audit " +
		"logging covers in code — not one deployment's `audit.policies` configuration, which can " +
		"additionally suppress publishing for a matched event without changing what's *covered* here.\n\n"

	out += renderRESTSection(ops)
	out += renderMCPSection(perms, bindings)
	out += renderKnownNonEvents()

	return out, nil
}

func renderRESTSection(ops []audit.Operation) string {
	out := fmt.Sprintf("## REST — %d audited operations\n\n", len(ops))
	out += "| Operation ID | Action | Category | Resource type | Resource identity |\n"
	out += "|---|---|---|---|---|\n"
	for _, op := range ops {
		var identity string
		switch {
		case op.RESTResourceParam != "":
			identity = fmt.Sprintf("path-derived (`%s`), available even on denial", op.RESTResourceParam)
		case op.NotInOpenAPISpec:
			// A non-spec operation (Exec, Wirelogs) is hand-wired outside
			// auditgen, so this table has no generic guarantee about when its
			// handler calls SetResource relative to its authz check — unlike
			// a generated body-carried create, which always runs its handler
			// (and thus SetResource) only after authz already passed.
			identity = "handler-supplied (non-spec operation, not a body-carried REST create) — see the handler for exact timing"
		default:
			identity = "handler-supplied on success (body-carried create; unavailable on a denied/failed request)"
		}
		out += fmt.Sprintf("| %s | `%s` | %s | %s | %s |\n",
			op.ID, op.Action, op.Category, op.ResourceType, identity)
	}
	out += "\n"

	out += fmt.Sprintf("### REST exemptions (%d)\n\n", len(apiaudit.RESTExemptions))
	out += "| Operation ID | Reason |\n|---|---|\n"
	ids := make([]string, 0, len(apiaudit.RESTExemptions))
	for id := range apiaudit.RESTExemptions {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		out += fmt.Sprintf("| %s | %s |\n", id, apiaudit.RESTExemptions[id])
	}
	out += "\n"
	return out
}

// boundRow is one (tool, scope) binding — a scope-collapsed tool contributes
// two rows, one per operation it fans out to. Rendering per-binding rather
// than per-tool-name is what makes this deterministic: a map keyed on tool
// name alone can hold only one of a scope-collapsed tool's two bindings, and
// which one survives depends on Go's randomized map iteration order.
type boundRow struct {
	tool, scope, opID, action string
}

func renderMCPSection(perms map[string]tools.ToolPermission, bindings map[audit.MCPBindingKey]audit.MCPBinding) string {
	boundToolNames := make(map[string]bool, len(bindings))
	rows := make([]boundRow, 0, len(bindings))
	for key, b := range bindings {
		boundToolNames[key.ToolName] = true
		rows = append(rows, boundRow{tool: key.ToolName, scope: key.Scope, opID: b.Operation.ID, action: b.Operation.Action})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].tool != rows[j].tool {
			return rows[i].tool < rows[j].tool
		}
		return rows[i].scope < rows[j].scope
	})

	var exempted, readOnly []string
	for name, perm := range perms {
		if boundToolNames[name] {
			continue
		}
		if perm.IsReadOnly() {
			readOnly = append(readOnly, name)
		} else {
			exempted = append(exempted, name)
		}
	}
	sort.Strings(exempted)

	out := fmt.Sprintf("## MCP — %d registered tools (%d state-modifying, %d read-only)\n\n",
		len(perms), len(boundToolNames)+len(exempted), len(readOnly))

	out += fmt.Sprintf("### Bound (%d tools, %d bindings)\n\n", len(boundToolNames), len(rows))
	out += "| Tool | Scope | Operation ID | Action |\n|---|---|---|---|\n"
	for _, r := range rows {
		scope := r.scope
		if scope == "" {
			scope = "—"
		}
		out += fmt.Sprintf("| `%s` | %s | %s | `%s` |\n", r.tool, scope, r.opID, r.action)
	}
	out += "\n"

	out += fmt.Sprintf("### Exempted (%d)\n\n", len(exempted))
	out += "| Tool | Reason |\n|---|---|\n"
	for _, name := range exempted {
		reason := apiaudit.MCPToolExemptions[name]
		if reason == "" {
			reason = "UNDOCUMENTED — declares a non-view action but has neither a binding nor an exemption reason"
		}
		out += fmt.Sprintf("| `%s` | %s |\n", name, reason)
	}
	out += "\n"

	out += fmt.Sprintf(
		"%d read-only tools (every declared action ends in `:view`) need no explicit exemption.\n\n",
		len(readOnly),
	)
	return out
}

func renderKnownNonEvents() string {
	return "## Known non-events\n\n" +
		"Cases where a real state-modifying request produces no audit event, or a diminished one, " +
		"by design or by a documented, unfixed gap:\n\n" +
		"- **Reads are out of scope.** Every GET operation on both surfaces, and MCP's `initialize` " +
		"session handshake.\n" +
		"- **A malformed path parameter never reaches audit on REST.** oapi-codegen's generated " +
		"wrapper binds path params and returns 400 before `HandlerMiddlewares` run " +
		"(`server.gen.go`), so a 400 from bad path binding is never audited.\n" +
		"- **`source_ip` is unobtainable for a direct (non-proxied) MCP client.** " +
		"`RequestExtra` carries no `RemoteAddr`; only `X-Forwarded-For`/`X-Real-IP` from " +
		"`Extra.Header` are available, and a direct client sets neither.\n" +
		"- **`X-Request-ID` and `source_ip` are both trusted from the client with no proxy check.** " +
		"`X-Request-ID` is hardened to require a parseable UUID (falling back to a generated one, " +
		"see `audit.RequestIDRejections`); `source_ip`'s `X-Forwarded-For`/`X-Real-IP` are taken at " +
		"face value — deploy behind a proxy that strips or overwrites both if `source_ip` needs to " +
		"be forensically trustworthy.\n" +
		"- **An invalid `scope` argument on a scope-collapsed MCP tool attributes the call to the " +
		"namespace-scoped operation with `result: failure`** — the tool call itself errors before " +
		"resolving a scope, so the event records the tool's default binding rather than the scope " +
		"the caller asked for. Harmless (nothing is silently permitted), just a label to be aware of " +
		"when reading a failure event's operation_id.\n" +
		"- **`pkg/mcp.NewSTDIO` registers no middleware** — neither audit nor the authz filter. Sound " +
		"today (there is no HTTP request and so no identity to attribute an event to), and it has no " +
		"production caller in this repo, but it is exported: whatever first wires MCP-over-stdio " +
		"gets an unaudited mutating surface until that's addressed.\n" +
		"- **`?filterByAuthz=false` records a service-layer authorization denial as `failure`, not " +
		"`denied`.** Opening a session with that query parameter skips the MCP authz filter " +
		"entirely, so a refusal surfaces as a `services.ErrForbidden` returned from the handler " +
		"rather than one of the filter's own sentinels — `classifyResult` has no way to tell that " +
		"apart from an ordinary failure. A `results: [denied]` query on the read path silently " +
		"misses these.\n" +
		"- **An HTTP-level 401 on `/mcp` emits nothing.** `NewUnauthenticatedMiddleware` is composed " +
		"into `APIMiddlewares` for REST but not into the MCP handler chain (`cmd/openchoreo-api/main.go`), " +
		"so an expired or missing token produces an `unauthenticated` audit event on REST and silence " +
		"on MCP. `mcpaudit.classifyResult`'s `ErrNoSubject → unauthenticated` only covers a request " +
		"that already passed HTTP auth and has no subject in its MCP session.\n"
}
