{{- if .Values.eventsCollector.enabled }}
{{- if .Values.eventsCollector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openchoreo-observability-plane.eventsCollector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-observability-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: events-collector
  {{- with .Values.eventsCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
