openapi: 3.0.3
info:
  title: OpenChoreo Security Scanner API
  description: |
    REST API for querying Kubernetes resource security posture findings.

    The Security Scanner watches Kubernetes resources (Pods, Deployments, StatefulSets, etc.),
    resolves parent controllers, runs Checkov policy checks, and stores findings.

    This API provides endpoints to query security findings grouped by resource,
    with support for pagination and filtering.
  version: 1.0.0
  contact:
    name: OpenChoreo
    url: https://github.com/openchoreo/openchoreo
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: http://security-scanner.openchoreo-system.svc.cluster.local:8080/api/v1
    description: In-cluster service

tags:
  - name: health
    description: Health check operations
  - name: posture
    description: Security posture findings

paths:
  /health:
    get:
      tags:
        - health
      summary: Health check
      description: Returns the health status of the security scanner service
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: healthy
                timestamp: "2025-01-15T12:00:00Z"
                version: v1.0.0

  /posture/findings:
    get:
      tags:
        - posture
      summary: List posture findings
      description: |
        Retrieves security posture findings grouped by Kubernetes resource.

        Findings are generated by scanning resolved parent controllers (e.g., Deployments, StatefulSets)
        using Checkov policy checks. Results include resource metadata, labels, and all associated findings.

        Supports pagination for efficient retrieval of large result sets.
      operationId: listPostureFindings
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          example: 1
        - name: page_size
          in: query
          description: Number of resources per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 50
          example: 50
        - name: namespace
          in: query
          description: Filter by Kubernetes namespace
          required: false
          schema:
            type: string
          example: default
        - name: name
          in: query
          description: Filter by resource name (supports wildcards)
          required: false
          schema:
            type: string
          example: web-*
        - name: labels
          in: query
          description: Filter by labels (format - key1=value1,key2=value2)
          required: false
          schema:
            type: string
          example: app=web,tier=frontend
        - name: sort_by
          in: query
          description: Field to sort by
          required: false
          schema:
            type: string
            enum:
              - created_at
              - updated_at
            default: updated_at
        - name: sort_order
          in: query
          description: Sort order
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
            default: desc
      responses:
        '200':
          description: Successfully retrieved posture findings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostureFindingsResponse'
              examples:
                withFindings:
                  summary: Resources with security findings
                  value:
                    resources:
                      - type: Deployment
                        namespace: default
                        name: web-app
                        uid: 12345678-1234-1234-1234-123456789012
                        resource_version: "12345"
                        created_at: "2025-01-15T10:30:00Z"
                        updated_at: "2025-01-15T11:45:00Z"
                        labels:
                          app: web-app
                          tier: frontend
                          environment: production
                        findings:
                          - id: 1
                            check_id: CKV_K8S_8
                            check_name: Liveness Probe Should Be Configured
                            severity: LOW
                            category: General
                            description: Ensure that Liveness Probe is configured
                            remediation: Add livenessProbe to container spec
                            created_at: "2025-01-15T11:45:00Z"
                          - id: 2
                            check_id: CKV_K8S_14
                            check_name: Image Tag should be fixed - not latest or blank
                            severity: MEDIUM
                            category: General
                            description: Image 'nginx:latest' has tag latest
                            remediation: Use a specific image tag instead of latest
                            created_at: "2025-01-15T11:45:00Z"
                      - type: StatefulSet
                        namespace: database
                        name: postgres
                        uid: 87654321-4321-4321-4321-210987654321
                        resource_version: "67890"
                        created_at: "2025-01-14T09:15:00Z"
                        updated_at: "2025-01-15T08:20:00Z"
                        labels:
                          app: postgres
                          tier: database
                        findings:
                          - id: 3
                            check_id: CKV_K8S_22
                            check_name: Use read-only filesystem for containers where possible
                            severity: LOW
                            category: General
                            description: Container does not use read-only root filesystem
                            remediation: Set readOnlyRootFilesystem to true in securityContext
                            created_at: "2025-01-15T08:20:00Z"
                    pagination:
                      page: 1
                      page_size: 50
                      total_items: 2
                      total_pages: 1
                      has_next: false
                      has_prev: false
                empty:
                  summary: No findings found
                  value:
                    resources: []
                    pagination:
                      page: 1
                      page_size: 50
                      total_items: 0
                      total_pages: 0
                      has_next: false
                      has_prev: false
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: Invalid page_size parameter
                message: page_size must be between 1 and 1000
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: Database error
                message: Failed to retrieve posture findings

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
        - version
      properties:
        status:
          type: string
          description: Health status of the service
          enum:
            - healthy
            - unhealthy
          example: healthy
        timestamp:
          type: string
          format: date-time
          description: Current server timestamp
          example: "2025-01-15T12:00:00Z"
        version:
          type: string
          description: API version
          example: v1.0.0

    PostureFindingsResponse:
      type: object
      required:
        - resources
        - pagination
      properties:
        resources:
          type: array
          description: List of Kubernetes resources with their security findings
          items:
            $ref: '#/components/schemas/ResourceWithFindings'
        pagination:
          $ref: '#/components/schemas/PaginationInfo'

    ResourceWithFindings:
      type: object
      required:
        - type
        - namespace
        - name
        - uid
        - resource_version
        - created_at
        - updated_at
        - labels
        - findings
      properties:
        type:
          type: string
          description: Kubernetes resource type
          enum:
            - Deployment
            - StatefulSet
            - DaemonSet
            - Job
            - CronJob
            - Pod
          example: Deployment
        namespace:
          type: string
          description: Kubernetes namespace
          example: default
        name:
          type: string
          description: Resource name
          example: web-app
        uid:
          type: string
          description: Kubernetes resource UID
          format: uuid
          example: 12345678-1234-1234-1234-123456789012
        resource_version:
          type: string
          description: Kubernetes resource version for change tracking
          example: "12345"
        created_at:
          type: string
          format: date-time
          description: Resource creation timestamp
          example: "2025-01-15T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Resource last update timestamp
          example: "2025-01-15T11:45:00Z"
        labels:
          type: object
          description: Kubernetes resource labels
          additionalProperties:
            type: string
          example:
            app: web-app
            tier: frontend
            environment: production
        findings:
          type: array
          description: Security findings for this resource
          items:
            $ref: '#/components/schemas/PostureFinding'

    PostureFinding:
      type: object
      required:
        - id
        - check_id
        - check_name
        - severity
        - created_at
      properties:
        id:
          type: integer
          format: int64
          description: Unique finding identifier
          example: 1
        check_id:
          type: string
          description: Checkov check identifier
          example: CKV_K8S_8
        check_name:
          type: string
          description: Human-readable check name
          example: Liveness Probe Should Be Configured
        severity:
          type: string
          description: Severity level of the finding
          enum:
            - CRITICAL
            - HIGH
            - MEDIUM
            - LOW
            - INFO
            - UNKNOWN
          example: MEDIUM
        category:
          type: string
          nullable: true
          description: Finding category
          example: General
        description:
          type: string
          nullable: true
          description: Detailed description of the finding
          example: Ensure that Liveness Probe is configured
        remediation:
          type: string
          nullable: true
          description: Suggested remediation steps
          example: Add livenessProbe to container spec
        created_at:
          type: string
          format: date-time
          description: When the finding was detected
          example: "2025-01-15T11:45:00Z"

    PaginationInfo:
      type: object
      required:
        - page
        - page_size
        - total_items
        - total_pages
        - has_next
        - has_prev
      properties:
        page:
          type: integer
          description: Current page number
          minimum: 1
          example: 1
        page_size:
          type: integer
          description: Number of items per page
          minimum: 1
          maximum: 1000
          example: 50
        total_items:
          type: integer
          description: Total number of items across all pages
          minimum: 0
          example: 42
        total_pages:
          type: integer
          description: Total number of pages
          minimum: 0
          example: 1
        has_next:
          type: boolean
          description: Whether there is a next page
          example: false
        has_prev:
          type: boolean
          description: Whether there is a previous page
          example: false

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type or category
          example: Database error
        message:
          type: string
          description: Detailed error message
          example: Failed to retrieve posture findings
