apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: email
spec:
  owner:
    projectName: gcp-microservice-demo
  type: Service

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: email
spec:
  owner:
    componentName: email
    projectName: gcp-microservice-demo
  containers:
    main:
      image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.3
      env:
        - key: DISABLE_PROFILER
          value: "1"
        - key: PORT
          value: "5000"
        - key: ENABLE_TRACING
          value: "1"
        - key: COLLECTOR_SERVICE_ADDR
          value: "openchoreo-observability-clickstack-hyperdx-otel-collector.openchoreo-observability-clickstack.svc.cluster.local:4317"
        - key: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "openchoreo-observability-clickstack-hyperdx-otel-collector.openchoreo-observability-clickstack.svc.cluster.local:4317"
        - key: OTEL_EXPORTER_OTLP_HEADERS
          value: "authorization=2c04a8a1-c7a4-445c-9919-ebd01289c6bd"

  endpoints:
    grpc-endpoint:
      type: gRPC
      port: 5000
      schema:
        type: gRPC
        content: |
          syntax = "proto3";

          package hipstershop;
          
          service EmailService {
              rpc SendOrderConfirmation(SendOrderConfirmationRequest) returns (Empty) {}
          }

          message OrderItem {
              CartItem item = 1;
              Money cost = 2;
          }

          message OrderResult {
              string   order_id = 1;
              string   shipping_tracking_id = 2;
              Money shipping_cost = 3;
              Address  shipping_address = 4;
              repeated OrderItem items = 5;
          }

          message SendOrderConfirmationRequest {
              string email = 1;
              OrderResult order = 2;
          }

---
apiVersion: openchoreo.dev/v1alpha1
kind: Service
metadata:
  name: email
spec:
  owner:
    componentName: email
    projectName: gcp-microservice-demo
  workloadName: email
  overrides: {}
