apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "security-scanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: security-scanner
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/component: security-scanner
    {{- include "security-scanner.selectorLabels" . | nindent 4 }}
