{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "security-scanner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "security-scanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: security-scanner
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
