apiVersion: batch/v1
kind: Job
metadata:
  name: apply-coredns-configmap
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      serviceAccountName: coredns-apply-sa
      containers:
        - name: kubectl
          image: {{ .Values.waitJob.image }}
          imagePullPolicy: IfNotPresent
          command:
          - kubectl
          args:
          - apply
          - -f
          - /config/coredns-configmap.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: coredns-config
      restartPolicy: Never
  backoffLimit: 4
