apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredns-apply-binding
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
subjects:
  - kind: ServiceAccount
    name: coredns-apply-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: coredns-configmap-role
  apiGroup: rbac.authorization.k8s.io
