apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredns-apply-binding
subjects:
  - kind: ServiceAccount
    name: coredns-apply-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: coredns-configmap-role
  apiGroup: rbac.authorization.k8s.io
