apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
spec:
  confMgmt:
    smartScaler: true

  dashboards:
    enable: {{ .Values.cluster.dashboard.enabled }}
    replicas: {{ .Values.cluster.dashboard.replicas }}
    version: {{ .Values.cluster.dashboard.version }}
    opensearchCredentialsSecret:
      name: opensearch-admin-credentials-secret

  general:
    version: {{ .Values.cluster.general.version }}
    httpPort: {{ .Values.cluster.general.httpPort }}
    serviceName: {{ .Values.cluster.general.serviceName }}
    setVMMaxMapCount: {{ .Values.cluster.general.setVMMaxMapCount }}

  nodePools:
  - component: data
    diskSize: {{ .Values.cluster.nodePools.data.diskSize }}
    pdb:
      enable: true
      minAvailable: {{ sub .Values.cluster.nodePools.data.replicas 1 }}
    replicas: {{ .Values.cluster.nodePools.data.replicas }}
    resources:
      limits:
        cpu: {{ .Values.cluster.nodePools.data.resources.limits.cpu }}
        memory: {{ .Values.cluster.nodePools.data.resources.limits.memory }}
      requests:
        cpu: {{ .Values.cluster.nodePools.data.resources.requests.cpu }}
        memory: {{ .Values.cluster.nodePools.data.resources.requests.memory }}
    roles:
    - data
    - ingest
  - component: master
    diskSize: {{ .Values.cluster.nodePools.master.diskSize }}
    pdb:
      enable: true
      minAvailable: {{ sub .Values.cluster.nodePools.master.replicas 1 }}
    replicas: {{ .Values.cluster.nodePools.master.replicas }}
    resources:
      limits:
        cpu: {{ .Values.cluster.nodePools.master.resources.limits.cpu }}
        memory: {{ .Values.cluster.nodePools.master.resources.limits.memory }}
      requests:
        cpu: {{ .Values.cluster.nodePools.master.resources.requests.cpu }}
        memory: {{ .Values.cluster.nodePools.master.resources.requests.memory }}
    roles:
    - master

  security:
    config:
      adminCredentialsSecret:
        name: opensearch-admin-credentials-secret
      securityConfigSecret:
        name: opensearch-security-config
    tls:
      http:
        generate: true
      transport:
        generate: true
