apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin-credentials-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.cluster.adminUsername | b64enc }}
  password: {{ .Values.cluster.adminUserPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-security-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  internal_users.yml: {{- (printf .Values.cluster.internalUsers (.Values.cluster.adminUserPassword | bcrypt)) | b64enc | nindent 4 }}
